### ISSUE TITLE
[Question] Will Autodrive also be available in FS22?

### ISSUE THREAD

**Issue by kferrano** [Stephan-S/FS19_AutoDrive#2125] opened 2021-11-21 14:19 UTC
**Question:**   
Will Autodrive also be available in FS22?

**Comment by fudoido** [comment] 2021-11-22 00:58
Dont know, but i will leave here the same suggestion that i left on courseplay github.....
Considering both mods are cooperating, that fs22 has a new ai that uses the basic functions of autodrive and courseplay, i suggested courseplay tem to talk with stephan and try to join forces this time around, creating a new coursedrive or autoplay mod, with just the more advanced features that fs22 ai doesnt have, like unloading from combines, silo compacting, shovel works, maybe keep the courseplay fieldwork path geneating tool as fs22 ai might not be good for non-squared fields.
Considering the work giants had to implement some sort of courseplay/autodrive features into the game, that could relieve a bit more work from the mod teams and focus on more advanced features instead.
For what i have seen from streamers on pre-launch, seems AI is using some sort of coordinates, and we can even select which way they face the map on arrival. a new version of courseplay/autodrive could be as simple (in my head, i know its not an easy task to program it) as the mod telling the game to " go X, Y and angle Z ". Find a way to mark the combines discharge point, make mod update its coordinates and mod tells AI go there. challenge gonna be if tractor/truck will keep updating position to reach, or if it stops every time a new coordinates value is inserted :/

**Comment by Iwan1803** [comment] 2021-11-22 16:51
Unfortunately, Giants failed to inform modders about changes in time. Through their behavior, they have also lowered the motivation enormously. That some now no longer have any desire to update their mods should be understandable.
So for now please understand that we currently can't say if there will be AD for LS22.

**Comment by andreasthu** [comment] 2021-11-23 12:12
Hallo iwan,
Let me say, AD is one of the most interesting and usefull mods in Ls19.
The new ai in 22 is (only) nice.
I were very happy to see your AD mod in Ls22,
But i also understand when you where angry about the comunication.
 Lg
Andreas

**Comment by derJan2001** [comment] 2021-11-23 16:27
Oh no ! The AI in 22 is terrible! The game between AD and CP is the best thing ever. One for the fields and one for the streets ... 
I like it.

**Comment by fudoido** [comment] 2021-11-23 22:19
my suggestion remains. dont feel bad about giants, many other companies ignore the modding community and even the gamers. i would say that at elast they are trying to give us what modders like you gave us before, and that is a good sign that they at least care a little more than some other companies.
if you really think on trying something for fs22, at least try to convince courseplay guys as well, i believe all of you together working on the same mod will be much more easier and less time consuming than each of you creating 2 separate mods and then making them work together like in fs19.
AI ingame is not the best, i hope giants will improve it over time, but what i would still love to have is the ability to collect from the combines and then go sell.
i have already tested and if we use game AI to start on the edge of a field and go sell in a looping route, it will wait in the edge of the field (where it was standing when creating the course) until the trailer gets filled. with this in mind, maybe creating a course for augers to collect from combine and dump in the trailer would be enough.
all i can say is, giants is trying to give players what is more popular in mods, at least for gameplay (not only courseplay/autodrive features, but also seasons and manual gears), and that should not let modders feel bad and give up, just think that it might actually free your time to do something different or better.
Seriously, join forces with CP team, you been working along to make both mods cooperate for fs19, get along and make a even better single courseplay/autodrive mod combined for fs22. think on features that the game AI does NOT have, and when you manage that then you can consider improving what the game AI has.
I know it will take time and loads of thinking, i wish i knew more about coding and help, i know you must learn about the way the game processes this new AI, but dont give up on making something magnificent again.

**Comment by slimshadey70** [comment] 2021-11-26 03:10
I would very much like to see courseplay and autodrive in fs22, for me thesse are the make or break mods that will decide whether i commit to fs22 or stay with fs19.   These mods are amazing and are just not something i am willing to work without.  The modders for this game make the game.  I feel strongly that giants needs to do more for their modders they seem to ignore them and have very little regard for what they do for their game.  I think the modders make the game, pure and simple.

**Comment by KCHARRO** [comment] 2021-11-26 16:45
I have always been faithful to Autodrive and Courseplay, no AI no matter how good and improved it was, it does not compare, nobody even reaches the soles of the feet to AD and CP ...

The guys at CP will update, they already confirmed ...

And I agree 1000% with @fudoido,

please ... don't let AD die, I feel like he lost something important, and incredibly as I write right now I have deep sadness and water in my eyes, work together guys ...

**Comment by KaaTrav** [comment] 2021-11-27 19:41
Oh... AutoDrive is just an incredible mod, especially for solo players, as well as on large maps... And the AD+CP tandem... In FS19, I can no longer imagine a game without BOTH mods - each in its own category. CP is work in the fields (combine harvester, plow and any other equipment), and with the help of your mod I make a network of ALL roads on the map with the ability to get from one corner of the map to any other. Yes, this function was also present in CP, but there it was necessary to write a bunch of segments, connect them, etc. Yes, it was possible to combine and then save the necessary routes, but... I've had up to a hundred routes on maps with productions! Your mod is simply irreplaceable in this regard!

With regard to FS 22... I do not know exactly how the game generates routes for AI, but... If they are initially sewn into the map, then perhaps they work more or less normally, but... In this case, I am not sure that the creators of new maps (or conversions of old ones) will make a sensible registration of routes for use with their maps... If the routes are "generated on the fly", then... It is also not a fact that they will work fine on mod maps.
Whether to team up with the CP creators is your decision, but, IMHO, it would be nice to coordinate your actions, in case they want to change their principle of creating routes to one close to yours... It might really be good to team up and work together, but again, it's YOUR personal decision, as are the CP teams.
But, in any case, I really hope that you will not abandon your brainchild! I can't imagine how I played FS17 without AutoDrive (unfortunately I didn't find out about it right away). But now, if I have nostalgia for FS17, then even in that version of the game I use AD, even though it is very simple there (in fact, only creating a network, without working with equipment, etc.), but even this is a huge plus. For all my favorite maps, to which even now I occasionally return to FS17, I have made the most detailed network of routes...
In any case, good game AI in terms of routes or bad, but it will NOT replace a manually created network, conducted exactly as it is convenient for ME or another player, with location points located in a specific corner of the field, etc.
I'M JUST BEGGING YOU! Please don't quit your project! I know players who only found out about your mod a month ago, but now they have no idea how they did without it!!!
Please make a continuation of your FS22 mod!
With respect and gratitude for your work, Anna.

**Comment by fudoido** [comment] 2021-11-28 01:07
@KaaTrav my thoughts the same.
courseplay is great for fieldwork, silo compacting, the new bale collection mode released for fs19, shovel works, and all those more detailed functions, but network wise, autodrive is much more simple to use and more effective. the only thing with autodrive courses that i miss from courseplay, is that CP manages better the way trailers approach and follow the combines. other than that, for long drive functions such as combine unload, store harvests in farm silos, go sell harvests, go from A to B, autodrive is king in setting up the network.
as about your doubt about the AI generated courses, for what i ahve seen so far from some modders that were streaming giants editor when it launched, it seems the new AI takes advantage of the traffic "splines" that were present before, added when creating the game in the editor, and they noticed this because they detected some new traffic splines with restrictions for combines.
dont remember which map he was checking, but there was a small covered bridge and regular traffic was able to go through it, but since combines are usually large and higher, it had that special "spline" going around the bridge through a small path in the river.
If this is the case, new AI is using the traffic splines, maybe there is a way to use them also for CP / AD ?
i also commented this on CP github about the splines, maybe it can be taken advantage of.
maybe we can see autodrive back for fs22, but i do understand it will take time as both stephan (and/or whoever is maintaining the mod now) and the CP team are doing all this work on free time and they also dont need any extra pressure to get things done, otherwise they might just get tired, stressed and abandon it completely.

**Comment by KaaTrav** [comment] 2021-11-28 10:21
> maybe we can see autodrive back for fs22, but i do understand it will take time as both stephan (and/or whoever is maintaining the mod now) and the CP team are doing all this work on free time and they also dont need any extra pressure to get things done, otherwise they might just get tired, stressed and abandon it completely.

I totally agree with you! I just decided to add my vision of the need for AD, despite the presence of CP and the difference in their functionality and direction of application (although the author or the authors of the mod know this perfectly well without me). And I am in no way rushing or trying to put pressure on the author! I know by myself that when I don't want to do something, and I am actively pressured into doing something, I want to do it out of spite or vice versa. Of course, if it's not related to my work, you can do it or lose your job there.
I just added my request to the existing ones...
P.S. Perhaps the only mod related to work in the fields, which I also lack, is the GPS mod from FS17 or its version Guidance Steering in FS19. I don't understand, is it really so difficult for developers to add this function by default?! This mod, even in the presence of CP, helped me very much in FS17/19 (mowing lawns that are not highlighted as fields, creating their own fields or expanding/combining existing ones (I don't like too curves, and it's not always possible to walk with a plow with my hands or I have to wipe the borders with landscape painting)). I hope it will be converted to FS22. After all, the functionality is simpler there...
I'm sorry that I wrote off topic at the end... ;-)

**Comment by Reiko40** [comment] 2021-11-28 13:02
Also ich würde mich freuen wenn es AD wieder geben wird. Die KI von Giants ist nicht wirklich das richtige. Man muss selber abtanken fahren und ständig findet er das Ziel nicht also ist Ad eine Bereicherung für den LS 22

**Comment by rohne83** [comment] 2021-11-29 15:51
The AI helper is much different from AD and especially CP. Granted, its purpose seems to overlap very much with AD functionality, but at least in FS22 it is very limited: you cannot control any settings, cannot send him to the combines/harvesters, you cannot remember exact waypoints, set parking locations, etc etc. The target group of this AI helper seems to be the people who don't want to or cannot (consoles) use sophisticated script mods with dozens of settings.
Of course they could have talked to you AD guys before, but on the other hand this would have meant a big danger of unwanted leakage of any info about this completely new feature. Totally understandable that Giants wanted to keep this totally internal as long as possible, and thus did NOT talk to you.
The technology behind the helper is completely different to AD (and CP) route networks anyway. It's rather like extending the pathfinding - which AD and CP only do on the fields - onto the whole map. Will be interesting how performance will be on 4x maps then... But keeping in mind the very restricted usability of this new helper, I don't see any alternative to have CP AND AD in FS 22 as well.

**Comment by Iwan1803** [comment] 2021-11-30 07:26
Liebe Community,
wir danken euch für euren Zuspruch. Um Spekulationen vorzubeugen und euch nicht länger warten zu lassen, möchten wir etwas verkünden:
das AD-Team arbeitet im stillen Kämmerlein daran, AD für LS22 fit zu machen.
Aktuell können wir noch nicht sagen, wann AD released wird.
It's done when it's done, aber lasst euch überraschen... 😎 

_Dear community,
we thank you for your encouragement. To prevent speculations and not to keep you waiting any longer, we would like to announce something:
the AD team is quietly working on getting AD ready for LS22.
Currently we can't say when AD will be released.
It's done when it's done, but let us surprise you... 😎_

**Comment by Dennis-02** [comment] 2021-11-30 11:07
Hallo Iwan,
schön, dass Autodrive für den LS 22 fit gemacht wird. Wie ist denn der aktuelle Stand? Kann man davon ausgehen, dass es noch Tage, Wochen oder Monate dauert? Klar kann keiner ein exaktes Release-Datum erwarten, allerdings ist ein grober Anhaltspunkt schon toll :)

**Comment by Iwan1803** [comment] 2021-11-30 11:54
> Aktuell können wir noch nicht sagen, wann AD released wird.

Was ist hieran nicht zu verstehen, das man nachfragen muss?

**Comment by kferrano** [comment] 2021-11-30 12:00
@Iwan1803 kann man sich als Tester bei euch bewerben?

**Comment by Iwan1803** [comment] 2021-11-30 13:21
Nur um AD früher zu haben als andere? Öhm, nein 😉

**Comment by fudoido** [comment] 2021-12-01 00:54
@Iwan1803 good news knowing AD will come to fs22 also :)
will the team still work together with CP team this version and make the 2 mods cooperate? or maybe find a even better way for them to use each other features? 

suggestion, would it be possible to make the vehicles approach combines for unload earlier than the actual unload feature?
make them follow the combine when tank reaches a set value and then drive to unload when the max value is reached, if you know what i mean?
in fs19 it only starts driving when capacity reaches the limit, and sometimes the vehicles are a bit too far from combine in the field and make the process take too long, having them following the combine at, 50% for example, and when reaching 100 they would then drive to unload under the pipe, would be a great addition to the AD mechanics.

**Comment by TobiHH78** [comment] 2021-12-01 09:58
> @Iwan1803 good news knowing AD will come to fs22 also :) will the team still work together with CP team this version and make the 2 mods cooperate? or maybe find a even better way for them to use each other features?
> 
> suggestion, would it be possible to make the vehicles approach combines for unload earlier than the actual unload feature? make them follow the combine when tank reaches a set value and then drive to unload when the max value is reached, if you know what i mean? in fs19 it only starts driving when capacity reaches the limit, and sometimes the vehicles are a bit too far from combine in the field and make the process take too long, having them following the combine at, 50% for example, and when reaching 100 they would then drive to unload under the pipe, would be a great addition to the AD mechanics.

You can do that already in FS19...There is a setting in the combine, at which fill level the unloader gets started. There is also a setting, that already a 2nd unloader is called at a certain fill level. I have set this to 30% and usually have no problem that my unloader reaches the combine in time.

**Comment by KCHARRO** [comment] 2021-12-01 13:13
> 

It's one of the 2 best news I've seen .......

Thanks guys ..... AD can't, and shouldn't be left behind.

**Comment by Azthek** [comment] 2021-12-02 16:13
Obviously good news and thanks to you guys for your efforts. 

I would like to ask - I dont expect the work on fs19 AD will continue as the priority has shifted (understandably), but the latest release 1.1.1.8 is stated to release also on ingame modhub - is that still the case? It would be nice to be able to get the last best  version of AD ingame (cant download mods externally).

Well anyway it is going to be, thanks again.

**Comment by Iwan1803** [comment] 2021-12-02 17:04
Since Giants has tightened the requirements for a release in the modhub, 1.1.1.8 was rejected.
Therefore this and all future versions will only be available here on github.

**Comment by rohne83** [comment] 2021-12-06 18:06
> > suggestion, would it be possible to make the vehicles approach combines for unload earlier than the actual unload feature? make them follow the combine when tank reaches a set value and then drive to unload when the max value is reached, if you know what i mean? in fs19 it only starts driving when capacity reaches the limit, and sometimes the vehicles are a bit too far from combine in the field and make the process take too long, having them following the combine at, 50% for example, and when reaching 100 they would then drive to unload under the pipe, would be a great addition to the AD mechanics.
> 
> You can do that already in FS19...There is a setting in the combine, at which fill level the unloader gets started. There is also a setting, that already a 2nd unloader is called at a certain fill level. I have set this to 30% and usually have no problem that my unloader reaches the combine in time.

And you can even use CP mode 2 for the unloaders with all its settings and mighty pathfinder, and let them hand over to AD for the road transport. Just following combines without unloading them would be a bit useless and even problematic as soon as you have more than one combine.

**Comment by Stephan-S** [comment] 2021-12-06 18:18
AD has active unloading capabilities since quite a long time now.
Merely the usablity is a bit cumbersome since it is hidden behind the 0% unload level in the settings.
Set the unload combine level to 0% and it will happily run alongside the combine just as it does for silage operations.
The pathfinder in AD does check for collisions along a planned path, even with respect to other pathfinder controlled vehicles on that field and thus is likely to have a harder time finding a route to the harvester compared to CP's algorithm as far as I have seen. Also it works with regardless of who is controlling the harvester, while CP's pathfinder/unloader can rely on having only to react to exactly their programmed manoeuvres by the combine.

But each approach has it's merits and drawbacks and since both are available to everyone, you should choose the one that best fits to your requirements.

**Comment by BigBlackBahamut** [comment] 2021-12-09 19:33
Wird es hier in diesen Projekt eingefügt oder erhält AutoDrive für den LS22 ein neues Projekt?

**Comment by Iwan1803** [comment] 2021-12-09 19:37
Einfach mal abwarten.... 😎

**Comment by Bobster82** [comment] 2021-12-12 09:45
Thanks AD team for continuing your work for fs22.
I know it is a lot of work to get things working again, but might there be any updates? Some parts working? 
Anyway, good luck!

**Comment by Iwan1803** [comment] 2021-12-20 06:43
AD for FS22: https://github.com/Stephan-S/FS22_AutoDrive

**Closed by Iwan1803** 2021-12-20 06:43 UTC
Labels: question
