### ISSUE TITLE
Park vehicle turns off vehicle when i want to take over

### ISSUE THREAD

**Issue by bojanh66** [Stephan-S/FS19_AutoDrive#913] opened 2019-11-21 15:28 UTC
When i press Park vehicle and if i want to take over the vehicle to continue driving it myself, i have to turn off AutoDrive, but it will turn off vehicle too, which is very annoying.
Could you change this so that vehicle remain turned on ?

**Comment by Roby1164** [comment] 2019-11-21 16:00
Before it was always on, and asked to turn it off, now it turns off and you want it to stay on ..... It seems to me that you are exaggerating a little ....
For me it is great that the vehicles at the end of AD work turn off, maybe you can see to put a command in the settings, whether to save fuel by switching off or not, like in the CP ...

**Comment by bojanh66** [comment] 2019-11-21 16:13
I dont know how it was before, i cant search through 1xxx opened/closed issues.
Then it would be maybe good idea to add an option turn on/turn off...just an idea.

**Comment by TyKonKet** [comment] 2019-11-21 16:17
This feature is still WIP, don't worry.
I'll let you know when it will be done and then a second feedback will be needed

**Comment by Martinnygaard** [comment] 2019-11-21 16:52
Possible a "Stop engine on/off" setting on vehicle specific settings page? :-)

**Comment by Michael170978** [comment] 2019-11-21 18:54
@TyKonKet  The feature is working fine. The problem is when you change your mind and you dont want that your vehicle drive to the park position then  the vehicle turn off the engine due driving.

**Comment by bojanh66** [comment] 2019-11-21 19:16
Thats what i was saying, but maybe my english is bad so i didnt explain 100% precisely.

**Comment by TyKonKet** [comment] 2019-11-21 20:06
@bojanh66 I understood what you meant, the point is that stopping motor when a vehicle is parked is not a new feature, it's a long time since this feature have been implemented and the bug (yes it's actually a bug what u are reporting) exists.
Any way as part of the 'Fuel Saving' feature I can also fix that.

**Comment by TyKonKet** [comment] 2019-11-21 21:55
Fixed with f786a09bc3538439016b48915d08fe5fdda295be

**Closed by TyKonKet** 2019-11-21 21:55 UTC
Labels: enhancement
