### ISSUE TITLE
Pickup and deliver not working properly

### ISSUE THREAD

**Issue by WubbeOP** [Stephan-S/FS19_AutoDrive#1011] opened 2019-12-12 21:30 UTC
AutoDrive Version: 1.0.7.0-33
Release or custom zip: Release
Map (if applicable): County Line
Vehicle / type (applicable): Truck and Trailer

The pickup and deliver function is not working correctly anymore. If I try to use it to sell grain from my bins, it will load at the bin trigger but than stop there until i turn it off and on again. Also, if I use it to transport grain from a fields side to the bins it just keeps driving the course without ever stopping at the load point. 
Using standard trucks and trailers.

**Comment by Despopanda** [comment] 2019-12-13 15:02
I have to say that I feel the same way!

I thought it would still be fixed, so far nothing will happen, it will be Christmas soon, and there are private things to do too, I can understand that, but I would like to thank you for doing a great job, keep going so, wish you all a nice holidays and a good slide.

**Comment by geo-luchs** [comment] 2019-12-13 22:22
I'm using 1.0.7.0-33, and I can get grain from silo, adn driving to sell point.
Also an unloader on a field, is unloading the harvester, and when full, he is driving to my silo or sell point.

**Comment by Despopanda** [comment] 2019-12-14 11:45
Hello geo-luchs

It's about the function (pick up and drop off)

Drive to the silo, have it filled, and should, for example, go to the cowshed with straw, everything set, and what happens only makes it once, and if it is to be done the second time, it stops after filling

Es geht ja um die funktion ( Abholen und Abliefern )
P.S My English is not that good, so I mostly do it with Google Translate

Hallo geo-luchs

Fahre zum Silo lasse es befüllen, und soll zum beispiel zum Kuhstall fahren mit Stroh, alles eingestellt, und was passiert, ermacht es nur einmal, und wenn er das zweitemal es machen soll bleibt nach dem befüllen stehen 

P.S Mein English ist nicht so gut deshalb mache ich es meistens mit Google Übersetzer

**Comment by geo-luchs** [comment] 2019-12-14 13:02
IHave seen it , too, in the  past.  But unfortunately Not With my latest  Tests. 

I have no idea,   Why it happens sometimes.
I had it , that he was driving back to silo, and filled again. I thought, he was already finished, gut Maybe I was wrong.

I have to Monitor it Today evening Again, and Check in sich combination it could happen.

**Comment by Despopanda** [comment] 2019-12-14 13:08
Hello geo-luchs

That would be great if you would give it a try, I'm very grateful for that. LG

Hallo geo-luchs

Das wäre super wenn du das mal Probieren würdest, dafür bin ich dir sehr dankbar. LG

**Comment by geo-luchs** [comment] 2019-12-14 16:53
Oh, I can reproduce it.
Loading straw from silo 3 times.
1st round it works. He is driving to silo, loading straw, driving to compound feed production, unloading straw.
driving back to silo, loading straw
and then switching off AD

It seems to be an error.

A scania R730 truck with trailer is delivering straw from same silo to pellets factory, and he was driving also the 2nd time. 

I tried the same with a normal tractor, and tractor is stopping at the loading point afterwards.

Both times ,I was NOT sitting in the truck.


No idea, why the truck is doing it correctly, but not the tractor.
MY loading points have not been changed since many versions. And it worked for me, too in older versions.

**Comment by Despopanda** [comment] 2019-12-14 17:00
Hello goe-luchs

Thank you for trying it, I hope that the bug will be fixed soon. It's no fun otherwise. I used an older version. Everything is fine. Version 1.0.7.0-16.

As soon as I or she find something, just let me know. Thanks

**Comment by geo-luchs** [comment] 2019-12-14 17:31
It's strange.

maybe in #994 it's the same issue.

I made several tests now.
Same tractor, different trailers, different targets.

It works fine with same tractor and both trailers, but also it fails with same tractor and both trailers.

In this case, only the target was different.
It works fine, when loading and unloading in Silo.

When unloading in compound food fabrication, it fails.

On the other hand, a truck Scania R730 with big trailer was working fine with loading at same silo and unloading at pellets factory.

Compound food factory and pellets factory are both GC compatible.

I will try later Truck with compound food factory.

**Comment by geo-luchs** [comment] 2019-12-14 19:25
Test with truck: it's also not working when choosing compound food factory as target.

So somehow it depends on the target.

**Comment by Despopanda** [comment] 2019-12-14 19:30
I guess we have to wait a few more days, unfortunately, I can not get it, I've already tried different trucks and tractors always come to the same

**Comment by Despopanda** [comment] 2019-12-15 14:06
Hello geo-luchs

If it now seems to go with the new update, I have just tried it, is going quite well so far, will do it after a few tests.

LG

P.S Thanks for the update

**Comment by MagnusMInuus** [comment] 2020-01-07 15:27
Habe dieses Problem auch. Mit diversen Standard Fahrzeugen getestet. Bis 1.0.6.6 funktionierte es, ab 1.0.6.7 das genannte Phänomen.

**Comment by Kaljitos** [comment] 2020-01-14 08:30
I have the same problem, tried on the initial map, without modifications, still becomes in place after 2 times loaded... going back to version 1.0.6.8 there is no such problem

**Closed** 2020-01-14 22:20 UTC
Labels: bug
