### ISSUE TITLE
Autodrive load route doesn't continue anymore

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#762] opened 2019-11-02 11:32 UTC
I am using AD to refefill my CP Lime spreader.
I got the newest updates from github.

It used to work just fine, but now at drive off, reach the fill trigger, fill the spreader and then just sits and wait. Almost like it does not know it's full? 

If i dissable and enable AD again, it drives back to the field and hands over the control to CP per usual.

![AD Refill](https://user-images.githubusercontent.com/26490587/68070253-70117b80-fd6c-11e9-8c2a-9b8f996018eb.png)

**Comment by Martinnygaard** [comment] 2019-11-02 11:34
Another CP tractor is spreading fertilizer, and that is doing excatly the same. 

Filling up, and then just waits.

![image](https://user-images.githubusercontent.com/26490587/68070295-f62dc200-fd6c-11e9-86a6-fee8d6fce1f5.png)

**Comment by RalfGorden** [comment] 2019-11-02 11:49
habe das selbe Problem

**Comment by Highlander1965** [comment] 2019-11-02 17:00
Very same problem with the latest update.

**Comment by plexten** [comment] 2019-11-02 18:14
Hi Stephan, der Modus "Abholen" geht definitiv nicht mehr richtig. Am GC Fermenter lädt er nicht mehr und fährt einfach durch. Bei der Version 1.0.6.6 geht es ohne Probleme nur mit der 1.0.6.6c nicht mehr.

**Comment by RalfGorden** [comment] 2019-11-02 20:51
hallo hab das selbe Problem

**Comment by Stephan-S** [comment] 2019-11-03 10:16
Could you confirm that this issue still exists with the latest source files?
I tried it with a lime spreader and with a seeder that has both seed and fertilizer storage and all got filled up and the vehicle always drove on.
Thanks for your feedback!

**Comment by Highlander1965** [comment] 2019-11-03 10:35
Im still having same issue, it loads lime at sell point but then waits using the latest source files.
![non movement](https://user-images.githubusercontent.com/56995066/68083823-82032500-fe25-11e9-958b-814ccd32476e.png)

**Comment by RalfGorden** [comment] 2019-11-03 11:22
hab jetzt nochmal getestet bei der 1.0.6.6c selbst gepackt geht bei dem Modus abholen und liefern nichts er fährt zwar zum beladepunkt aber läd nichts auf  bei der 1.0.6.6 geht alles

**Comment by RalfGorden** [comment] 2019-11-03 11:44
hab jetzt nochmal getestet bei der 1.0.6.6c selbst gepackt geht bei dem Modus abholen und liefern nichts er fährt zwar zum beladepunkt aber läd nichts auf bei der 1.0.6.6 geht alles

**Comment by Stephan-S** [comment] 2019-11-03 11:55
@RalfGorden Bitte genau beschreiben:
Welches Fahrzeug / Gerät
Welcher Trigger
Was soll geholt werden

Ich kann es derzeit nicht nachstellen

**Comment by evansv2** [comment] 2019-11-03 12:13
Yeah same here, doesnt refill anymore

latest version downloaded 15 minutes ago

https://www.youtube.com/watch?v=0KQ2FgH0moQ

**Comment by Stephan-S** [comment] 2019-11-03 12:16
Oh,  so is this only happening when started via CP?

**Comment by evansv2** [comment] 2019-11-03 12:20
> Oh, so is this only happening when started via CP?

That I'm not sure Stephan, I just know the one I was using last night, nov 2 version, when used with CP would  not fill up, and when I backed up and did it manually it Filled Up OK, so Yeah CP is messed up, but this fresh version, doesnt even reload manually

check this video 
https://www.youtube.com/watch?v=jM7wd2iK0r8

**Comment by RalfGorden** [comment] 2019-11-03 12:24
Standard Traktor Spiel auf der Multimap  Strohladetrigger auf dem hof aber auch Flüssigdünger läd er nicht mehr was in der 1.0.6.6 alles ging

**Comment by evansv2** [comment] 2019-11-03 16:43
> Oh, so is this only happening when started via CP?

Everything is good, problem was I placed the Target way too close to the tanks, it needs to be placed way way further up, since the tool was very long, the trigger didnt kick because of that

**Comment by Stephan-S** [comment] 2019-11-03 16:51
Yeah, was about to tell you that but I quickly changed the code so that it would work in the radius of the destination. So will work this way tomorrow :-)

**Comment by evansv2** [comment] 2019-11-03 17:39
> Yeah, was about to tell you that but I quickly changed the code so that it would work in the radius of the destination. So will work this way tomorrow :-)

Stephan seeder works 100% , fertilizer is playing tricks though
manually loads with the R trigger,, with AD seems to just drive like his late for a date Barbara Walters 

here is the video reference
https://www.youtube.com/watch?v=UoM9aGhnfyg

**Comment by evansv2** [comment] 2019-11-03 17:47
> > Yeah, was about to tell you that but I quickly changed the code so that it would work in the radius of the destination. So will work this way tomorrow :-)
> 
> Stephan seeder works 100% , fertilizer is playing tricks though
> manually loads with the R trigger,, with AD seems to just drive like his late for a date with Barbara Walters
> 
> here is the video reference
> https://www.youtube.com/watch?v=UoM9aGhnfyg

oh never mind, I had to set the maximum trigger distance to like 100meters, my bad, little to quick on reporting, everythign is good , radius destination is definetly good, because sometimes the trigger is like, way back or in front

**Comment by Dzi4d3k** [comment] 2019-11-03 20:09
@evansv2 then you can close issue to help authors clean resolved ones :)

**Comment by evansv2** [comment] 2019-11-03 20:50
> @evansv2 then you can close issue to help authors clean resolved ones :)

 Alright alright I'm going I know you guys hate my guts

**Comment by evansv2** [comment] 2019-11-03 20:56
> @evansv2 then you can close issue to help authors clean resolved ones :)

This is not my issue , There for I cannot close it

**Comment by Dzi4d3k** [comment] 2019-11-03 21:04
Yes, indeed. Sorry for that.

**Comment by Martinnygaard** [comment] 2019-11-04 05:34
Hi guys.

The issue is still present for me - and i cannot reopen the issue..
This is the newest files (downloaded 10 minutes ago)

This tractor was driven only by AD (not CP)
Did exactly as last time. Drive towards refill point - refill fertilizer - drive a little furter - refill seed and then wait untill i restart AD.

![AD Refill 2](https://user-images.githubusercontent.com/26490587/68101279-18d6ec80-fecd-11e9-80c6-869086c0dd5d.png)

![AD Refill](https://user-images.githubusercontent.com/26490587/68101283-1d9ba080-fecd-11e9-8900-4449d428ff2c.png)

**Comment by evansv2** [comment] 2019-11-04 10:38
> Hi @TyKonKet and @Stephan-S
> 
> The issue is still present for me - and i cannot reopen the issue..
> This is the newest files (downloaded 10 minutes ago)
> 
> This tractor was driven only by AD (not CP)
> Did exactly as last time. Drive towards refill point - refill fertilizer - drive a little furter - refill seed and then wait untill i restart AD.
> 
> ![AD Refill 2](https://user-images.githubusercontent.com/26490587/68101279-18d6ec80-fecd-11e9-80c6-869086c0dd5d.png)
> 
> ![AD Refill](https://user-images.githubusercontent.com/26490587/68101283-1d9ba080-fecd-11e9-8900-4449d428ff2c.png)

try placing your target there , thats what I did for it to catch, cause it has to be one the refill course
bbecause the tool size and its trigger is way back

Thats what I did for it to work , try placing target where the red circle is
![image](https://user-images.githubusercontent.com/55886626/68114936-4d1bce80-ff08-11e9-898f-ab8bbe9c3bb2.png)

**Comment by evansv2** [comment] 2019-11-04 10:41
@Stephan-S  I take it the issue is, when AD is in driving to refill course, looks for trigger and refills it, but when it goes to second course to comeback (and the tool is still way in the back (the huge tools)), during this phase its no longer searching for trigger? I didnt look at the code, Im just speculating thats whats hapening

**Comment by evansv2** [comment] 2019-11-04 10:44
![image](https://user-images.githubusercontent.com/55886626/68115280-16928380-ff09-11e9-94e6-ddd5f60b95aa.png)
 BTW when switching this option to 50, or 100 while AD is running it crashes so becarefull not to have AD turned on while switching trigger distance

**Comment by jala15** [comment] 2019-11-04 13:27
It happens the same to me. I've been doing a bit of research and found that in a buying silo it doesn't continue if set to wait if silo is empty. Here is a video showing it: https://youtu.be/Q7qGzL_gtGE
Have been looking for the code causing it but only found the following code line is not giving the expected true when full: https://github.com/Stephan-S/FS19_AutoDrive/blob/7ce661ad9ca1351d34dbf1cab58c11906a72887b/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua#L134
@Stephan-S I haven't had time for more testing but I let you it here so you know where to investigate if you want. 
Thank you.

**Comment by evansv2** [comment] 2019-11-04 13:37
> It happens the same to me. I've been doing a bit of research and found that in a buying silo it doesn't continue if set to wait if silo is empty. Here is a video showing it: https://youtu.be/Q7qGzL_gtGE
> Have been looking for the code causing it but only found the following code line is not giving the expected true when full:
> 
> https://github.com/Stephan-S/FS19_AutoDrive/blob/7ce661ad9ca1351d34dbf1cab58c11906a72887b/FS19_AutoDrive/scripts/AutoDriveTrailerUtil.lua#L134
> 
> 
> @Stephan-S I haven't had time for more testing but I let you it here so you know where to investigate if you want.
> Thank you.

Through the roof ehh?  :))))

**Comment by Martinnygaard** [comment] 2019-11-04 16:19
> try placing your target there , thats what I did for it to catch, cause it has to be one the refill course
> because the tool size and its trigger is way back
> 
> Thats what I did for it to work , try placing target where the red circle is, way way front

It is the same for a small fertilizer with only one fill type - so size is eliminated. 
And i know for sure that thes excatly setup has worked before (with small and big equipment.) :-)

![AD Refill 3](https://user-images.githubusercontent.com/26490587/68137239-ee198200-ff26-11e9-9d8c-b350e205bdc8.png)


But as @jala15 mentioned, then changing "if silo is empty" to "Continue". Thanks a lot for that advise! 

@Stephan-S , i guess that will be a bug? Isn't that primarily for trailers emptying a silo for ex. sell routes?

**Comment by Stephan-S** [comment] 2019-11-04 16:53
@jala15 thanks for pointing out this line.
I fixed it now. 
Damn copy paste error.
I always had the continue option set to true so I never noticed it

**Closed** 2019-11-10 08:39 UTC
