### ISSUE TITLE
cannot select targets

### ISSUE THREAD

**Issue by fudoido** [Stephan-S/FS19_AutoDrive#13] opened 2019-03-29 02:21 UTC
well, seems im the first to post an issue lol.
first of, thanks for working out this mod for fs19, i never really got into it on fs17 because i always been a courseplay user, but decided to give a trial run with your mod this time.
i will try your mod for courses driving, and courseplay for the more technical jobs, like field work, transfer bins work, etc :P
ok, time for my bug report......
made a few courses, all conected and named (targeted) to the places i wanted to test.
My problem now is, when i click the arrows to select the targets i named and recorded, even though they are conected to the "main" course properly, i dont get the targets to show up on the HUD, and due that i cant select them to start auto drive.
at first i thought it was just the target name not showing up, but it actually doesnt select any, because the button to start auto drive keeps grayed out.
Dont know how active you will be updating the mod, but hope to hear from you soon, and once again thanks for sharing your work with the community.

**Comment by Stephan-S** [comment] 2019-03-29 09:30
hello,  I am hoping that this is just an issue with the usage of the mod and nothing wrong with the code. But you are actually the second guy to alert me to that problem. I have never been able to recreate this situation, so just to clarify that you were doing everything the 'right' way.
First you select edit mode.
Then you press record and start driving.
Then either while you are still recording or afterwards, you click on 'new target', type in a name and press the enter key.
At that point, the name of the target should already appear on top of the current node and also inside the HUD.

Then after you stopped recording. Click the recalculate button.
Now you should be able to start a driver to that target.

Could you please send me the log file and the config.xml that AutoDrive creates in your savegame folder?
As for now, I don't habe enough information to tackle the problem. Thank you

**Comment by fudoido** [comment] 2019-03-29 18:26
press record button, drive course, name the target at desired location, name shows on top of waypoint as supposed, drive the remain of the course, stop recording, conect to any other recorder paths, save, recalculate routes, and when pressing the arrows to select target nothing selects.
sending the config file, but am not able to see a log file. can you tell me the correct name or path to find it?
https://drive.google.com/open?id=1MwtIr_inFfddJ8a3fJGTgf5s1Ao3hJMP

**Comment by Stephan-S** [comment] 2019-03-29 18:47
For some reason your first mapMarker was missing. Or rather your first map marker (Store) started with index 2 in the config file.
There must be some error in the code to let that happen. Here in the meantime, i fixed your config file so you can use it: https://drive.google.com/open?id=1MwtIr_inFfddJ8a3fJGTgf5s1Ao3hJMP

**Comment by fudoido** [comment] 2019-03-29 19:39
apreciate the gesture. will keep an eye on updated version and help out with bugs. :)
will test the fixed xml soon.

**Comment by Sibesiech** [comment] 2019-03-29 21:51
Hi There.
At first, big thanks for your effort.
Ran into the same issue. Im on a custom map (Mercury_Bauernhöf) and started using your mod with trying to create a mapMarker. So far i had no regular routes (MapNodes) so i could not do it. Gues this has something to do with the mentioned bug.
As of now i can not target any mapMarker. 
Can you state how you fixed the XML of @fudoido, so I and others can do it on our own for now?

**Comment by Sibesiech** [comment] 2019-03-29 22:17
New insights.
Restarted my savegame and all mapMarkers were gone. Created some new ones and now it is working.
mapmarkers now look as shown in following block.
 `        <mapmarker>
            <mm1>
               ...
            </mm1>
            <mm2>
               ...
            </mm2>
       ...
        </mapmarker>`
Before they startet with:
`<mm8> ... </8mm><9mm>...</9mm>`

**Comment by Stephan-S** [comment] 2019-04-01 11:09
Hey @Sibesiech . Do you have any insights as to what 'unregluar' or even regular usage caused the wrong mapMarker indexing? If you could pinpoint it to certain usage behaviour I would have a better chance at finding this error. Thank you!

**Comment by Sibesiech** [comment] 2019-04-03 15:16
So then
I could reproduce the error: 

1. Start a new map where you dont have any waypoints.
2. Switch to a vehicle
3. Open AutoDrive edit-mode.
4. Click button to create a mapmarker. (Menu to enter name for mapmarker will open)
5. Enter some name and confirm by pressin ENTER key. (No mapmarker will appear in config.xml)
6. Menu for mapmarker will close.
7. Now recorde some waypoints.
8. Create a new mapmarker on one waypoint. -> This one will appear in config.xml with index 2.

So i gues the bug is letting players create mapmarkers without checking if there are any waypoints.
Hope this helps. 

Again thank you for this mod. I like it more than courseplay because the vehicles find their way whithout me selecting exact route.

Cheers

**Comment by Stephan-S** [comment] 2019-04-05 16:55
Thank you, found and fixed the bug! That description made it quite easy. Thank you very much.
Will be fixed in next release

**Closed by Stephan-S** 2019-04-05 16:55 UTC
