### ISSUE TITLE
New HUD

### ISSUE THREAD

**Issue by raxtor** [Stephan-S/FS19_AutoDrive#448] opened 2019-09-04 19:45 UTC
Hi @Stephan-S,
thx for new HUD, but there is some big issue with node deleting... its able delete whole network..

**Comment by raxtor** [comment] 2019-09-04 19:55
![fsScreen_2019_09_04_21_52_26](https://user-images.githubusercontent.com/831266/64286733-6337fd80-cf5e-11e9-8741-b273cc18c214.png)
![fsScreen_2019_09_04_21_52_41](https://user-images.githubusercontent.com/831266/64286735-6337fd80-cf5e-11e9-91cb-0b09cee7b370.png)
![fsScreen_2019_09_04_21_52_52](https://user-images.githubusercontent.com/831266/64286737-6337fd80-cf5e-11e9-8165-3fc303bfabc5.png)
Also "target list seems corrupted" and filltype works strange.. somewhere is filltype list incoplet, somewhere is not present

**Comment by raxtor** [comment] 2019-09-04 19:59
Maybe leave old one and maka possibility switch to new one till problems will be fixed as hotfix..

**Comment by Stephan-S** [comment] 2019-09-04 20:07
Hotfix for deleting waypoints is out.
But target list isn't corrupted. You just have to scroll up.
Currently the first entry is always the selected one. So if you selection is the last in the list, it will be the only element you see.
I will take care if that in the future.
Same with the filltype selection. You just have to scroll up

**Comment by raxtor** [comment] 2019-09-04 20:09
ah, ok... will test it... not familiar with that yet... but it will be source of problems probablly

**Comment by ddiis** [comment] 2019-09-04 20:18
Wrong icons on combine mode and Loading mode

In pic text - "Combine unload", icon - "Loading in" ? Dont know english text.
![image](https://user-images.githubusercontent.com/4257956/64288057-c8ddb700-cf69-11e9-951f-6d457a5240ed.png)

And when im click add group (plus in labels list) - all game interface removes, ESC btn - show again.

![image](https://user-images.githubusercontent.com/4257956/64288174-1bb76e80-cf6a-11e9-9ac2-f6baefb2275b.png)

**Comment by raxtor** [comment] 2019-09-04 20:19
@Stephan-S Node deleting is fixed by hotfix..

**Comment by Stephan-S** [comment] 2019-09-04 20:28
@ddiis Hey, thank you. Fixed the mode icon. But could you send me a log when your hud disappears? I can't reproduce this right now. Thank you

**Comment by Stephan-S** [comment] 2019-09-04 20:33
I'm Off for today. for now, you can Display new Markers by moving the hud.
I will fix this tomorrow. Thanks

**Comment by ddiis** [comment] 2019-09-04 20:34
No errors in log :( I think its must open "add Group dialog", but nothing. Maybe another language game client?
video https://monosnap.com/file/eCDM2qQVFS0JIy9n2Vdpaf5UrDZfpH

**Comment by raxtor** [comment] 2019-09-04 20:48
> Hotfix for deleting waypoints is out.
> But target list isn't corrupted. You just have to scroll up.
> Currently the first entry is always the selected one. So if you selection is the last in the list, it will be the only element you see.
> I will take care if that in the future.
> Same with the filltype selection. You just have to scroll up
Its possible scroll by mouse wheel, but not possible select target from scrolled targets...

**Comment by raxtor** [comment] 2019-09-06 05:06
@Stephan-S it seems there is some trouble with waypoint list... new created waypoints are not shown there from this patch...
![fsScreen_2019_09_06_05_41_07](https://user-images.githubusercontent.com/831266/64402334-d764c500-d074-11e9-8243-e29435b91d72.png)
![fsScreen_2019_09_06_07_04_01](https://user-images.githubusercontent.com/831266/64402335-d7fd5b80-d074-11e9-8f8b-97b4d5b27123.png)

**Comment by raxtor** [comment] 2019-09-08 21:16
Update network button is invisible but working in no edit mode...
![fsScreen_2019_09_08_23_15_19](https://user-images.githubusercontent.com/831266/64494544-9cd67480-d28e-11e9-9f0e-d2a9ca0f9bf2.png)

**Comment by Martinnygaard** [comment] 2019-09-16 08:33
Eill it be possibily to increase the drop down menu width, to allow for longer destination names?
The wiothj on the HUD it self is just fine as it is now - only when showing the drop down window i would prefer a wider window.

![image](https://user-images.githubusercontent.com/26490587/64943881-25e04380-d86d-11e9-9a7a-7c10d2114a37.png)
The buttom five destinations is 5 different load/unload points on the TMR Mixer.

**Comment by ploughedfieldman123** [comment] 2019-09-19 17:05
I have not played fs2019 for a while and also I see this AutoDrive has been updated a lot, But I dont know what the loops are   or this P  parking is about, can someone do a short english video tutorial it would be most appreciated

**Comment by geo-luchs** [comment] 2019-09-23 05:05
I'm now using 1.0.5.8:

Invisible Update Button cannot be used anymore. Now you have to switch in Edit mode.

The parking function "P" can be used to define for each vehicle his own waypoint as parking position which is directly assigned to this button "P".

Please select one waypoint in the upper target list, then press right mouse button on "P". P"P will by shown now, when a parking position is defined for the vehicle in bold letters.

From now on, you can send the vehicle to his parking position with pressing "P" only, without selecting any waypoint in target list, and doesn't matter, which mode is selected. The mode will be automatically switched to "Drive"

**Maybe this issue can be closed?
It's very old, and most of the mentioned issues here are fixed in 1.0.5.8.**

It would be easier for Stephan to have less open issues.

Only the list width could be increased, I think , too. Espacially in the current released version there are 2 more icons which are reducing the width for the names itself.

**Comment by ploughedfieldman123** [comment] 2019-09-23 07:35
> I'm now using 1.0.5.8:
> 
> Invisible Update Button cannot be used anymore. Now you have to switch in Edit mode.
> 
> The parking function "P" can be used to define for each vehicle his own waypoint as parking position which is directly assigned to this button "P".
> 
> Please select one waypoint in the upper target list, then press right mouse button on "P". P"P will by shown now, when a parking position is defined for the vehicle in bold letters.
> 
> From now on, you can send the vehicle to his parking position with pressing "P" only, without selecting any waypoint in target list, and doesn't matter, which mode is selected. The mode will be automatically switched to "Drive"
> 
> **Maybe this issue can be closed? It's very old, and most of the mentioned issues here are fixed in 1.0.5.8.**
> 
> It would be easier for Stephan to have less open issues.
> 
> Only the list width could be increased, I think , too. Espacially in the current released version there are 2 more icons which are reducing the width for the names itself.

what about that loop icon  how do we use that

**Closed** 2019-10-03 16:53 UTC
