### ISSUE TITLE
planning routes

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#204] opened 2019-06-09 10:45 UTC
I know this is not an issue, but I didnt know where to ask my problem. in the 1st snapshot below I want tractor to turn right where yellow line shows as thats shortest way to destination. 

<a href="https://ibb.co/MpfQptJ"><img src="https://i.ibb.co/Gk9Nk8r/cows1.jpg" alt="cows1" border="0"></a>

this is the route I want it to make 

<a href="https://ibb.co/rMWBBg0"><img src="https://i.ibb.co/Qn5WWZQ/cows2.jpg" alt="cows2" border="0"></a>

but it carry on up to this right well past where I wanted it to turn

<a href="https://ibb.co/ZXY5KWL"><img src="https://i.ibb.co/7CRPV2Y/cows3.jpg" alt="cows3" border="0"></a>

this is the destination its going to but why not take 1st turn right as thats shortest route how can I fix that 

<a href="https://ibb.co/VjKJLdH"><img src="https://i.ibb.co/C1rmwqJ/cows4.jpg" alt="cows4" border="0"></a>

**Comment by Stephan-S** [comment] 2019-06-09 10:49
Upload your config.xml please.
But I am sure that this is caused by your AutoDrive settings.
There are two settings which can cause this.
One is the setting to 'Avoid other targets', which will cause him to driver the longer route if there is another destination on the shorter one.
The second option is 'Use fastest route'. This will try to calculate the time it takes the driver to drive both roads and this will be influenced heavily by sharp turns.

So try playing around with these options and remember to recalculate routes after changing this.

Best regards,
Stephan

**Comment by ploughedfieldman123** [comment] 2019-06-09 10:55
Hi stephan many thanks for replying so fast most appreciated. I still get a bit confused with all those settings  when you do a ctrl+alt+0   

here is my config file   http://www.filedropper.com/autodrivemarwellmanorfarmconfig

**Comment by Stephan-S** [comment] 2019-06-09 10:58
Yeah, like I said. Switch these two settings either in gui too 'No' or in file to '1' and recalculate

<useFastestRoute>1.000000</useFastestRoute>
<avoidMarkers>1.000000</avoidMarkers>

**Comment by ploughedfieldman123** [comment] 2019-06-09 11:18
> Yeah, like I said. Switch these two settings either in gui too 'No' or in file to '1' and recalculate
> 
> useFastestRoute 1.000000
> avoidMarkers1.000000

How do you mean  or in file to 1

**Comment by Stephan-S** [comment] 2019-06-09 11:25
> did you find any problems with my config file

No



> How do you mean or in file to 1

The config file you send me contains two line which start with 'useFastestRoute' and 'avoidMarkers' and there you will see that they are set two 2 instead of one. So instead od doing this in game in the menu you could also change this in the file. But there is no point to it if you know what to change in the menu. Just change it there and ignore the file if you don't really understand what to change there, please

**Comment by ploughedfieldman123** [comment] 2019-06-09 11:28
> > did you find any problems with my config file
> 
> No
> 
> > How do you mean or in file to 1
> 
> The config file you send me contains two line which start with 'useFastestRoute' and 'avoidMarkers' and there you will see that they are set two 2 instead of one. So instead od doing this in game in the menu you could also change this in the file. But there is no point to it if you know what to change in the menu. Just change it there and ignore the file if you don't really understand what to change there, please

Ok many thanks stephan  I understand you now.  just another small point, is there a time delay on when in combine mode, how long it takes for a tractor to go to combine to empty it, as it seems to wait ages before going to empty combine, even though combine is 100% full with pipe out

**Comment by Stephan-S** [comment] 2019-06-09 11:29
No, no delay. Just calculating the path. Does it find a route or does it drive through the fruit?

**Comment by ploughedfieldman123** [comment] 2019-06-09 11:30
well find a route mostly, but it just seems to take ages before it go to combine

**Comment by Stephan-S** [comment] 2019-06-09 11:46
I would appreciate it if you could make a short clip of this behaviour. And stay inside the driver while recording.
Also if you could send me the savegame of the moment before you record, so i can recreate the situation.
Normally the driver should start driving in a matter of 1-2 seconds

**Comment by ploughedfieldman123** [comment] 2019-06-09 11:51
> I would appreciate it if you could make a short clip of this behaviour. And stay inside the driver while recording.
> Also if you could send me the savegame of the moment before you record, so i can recreate the situation.
> Normally the driver should start driving in a matter of 1-2 seconds

Ok  when I have a field of wheat or barley or crops. I will do that as I dont have any fields yet what need harvesting.

**Comment by Soilaq** [comment] 2019-06-09 12:10
I'm experiencing the same as you ploughedfieldman123, but I wouldn't call it forever, like 20-30 secs maybe. Gonna take a look at your video when you get too it :)

**Comment by Stephan-S** [comment] 2019-06-09 12:13
One important thing to consider here is what the driver is displaying as status in the HUD
So if he is displaying 'Wait for combine' then he is still idle
But if he is displaying 'Drive to combine' then he is busy recalculating if he is still standing

The question is in which state he is when you experience these long idle times

**Comment by ploughedfieldman123** [comment] 2019-06-09 12:15
> One important thing to consider here is what the driver is displaying as status in the HUD
> So if he is displaying 'Wait for combine' then he is still idle
> But if he is displaying 'Drive to combine' then he is busy recalculating if he is still standing
> 
> The question is in which state he is when you experience these long idle times

Its when it says  he is displaying 'Drive to combine

**Comment by Stephan-S** [comment] 2019-06-09 12:16
alright, then he is obviously having problems calculating a good route.
So again, I will be very interested in a savegame when you get to that point :-)
Thanks in advance!

**Comment by ploughedfieldman123** [comment] 2019-06-09 12:18
> alright, then he is obviously having problems calculating a good route.
> So again, I will be very interested in a savegame when you get to that point :-)
> Thanks in advance!

Ok I am now sowing some wheat in a field to test it will get back to you when its done. whats the best program to record a video

**Comment by Stephan-S** [comment] 2019-06-09 12:20
To be honest, video is not as important as getting the savegame from you.
So please be sure to save the game before starting to harvest the field. This way I can best reproduce the scenario

**Comment by ploughedfieldman123** [comment] 2019-06-09 12:22
> To be honest, video is not as important as getting the savegame from you.
> So please be sure to save the game before starting to harvest the field. This way I can best reproduce the scenario

ok as Im not very good at doing a video

**Comment by ploughedfieldman123** [comment] 2019-06-09 17:06
> To be honest, video is not as important as getting the savegame from you.
> So please be sure to save the game before starting to harvest the field. This way I can best reproduce the scenario

Hi Stephan here is my savegame, I am playing on Marwell Manor map. and the field ready for harvesting of wheat is Field 19  

http://www.filedropper.com/savegame1

**Comment by Knowen** [comment] 2019-06-10 06:47
I have a related issue:
![Pathfinding_issue](https://user-images.githubusercontent.com/47173160/59177147-6ee07780-8b5b-11e9-8630-394ff4f2df9b.png)

My driver is coming from the green arrow and the target destination is at the end of the red arrow. The shortest and fastest way is to follow the blue arrow, but the driver will always try to take the purple arrow. I tried it with the option fastest route and shortest route. Always the same. All waypoints are correctly connected. i checked it triple (2 times in game, 1 time in the editor).
I also edited my street network on an other location just to be able to recalculate it. Still the same issue. 

No error in the log file.

_Tested with Version 1.0.3.1_

**Comment by Stephan-S** [comment] 2019-06-10 08:28
@Knowen could you please send me the config file, then I will have a look at it

**Comment by ploughedfieldman123** [comment] 2019-06-10 08:29
did you receive my save game Stephan. can you let me know what you find out

**Comment by Stephan-S** [comment] 2019-06-10 08:35
@ploughedfieldman123  yes, I did thanks. But in your savegame there are no vehicles set up to harvest field 19 and unload the combine.
I will set them up manually this time, but generally I don't have time to do this for everyone :-( . The optimal way is for you to only upload savegames where everything is already set up and where you know for sure that there will be an error when the AutoDrive driver goes to unload the next time.
This way I just have to enable the helper/courseplay and enable AutoDrive on the driver and can see what's going wrong.
With your savegame I have to do all of this manually and I don't know if this will fail/would fail on your pc.

**Comment by ploughedfieldman123** [comment] 2019-06-10 08:39
> @ploughedfieldman123 yes, I did thanks. But in your savegame there are no vehicles set up to harvest field 19 and unload the combine.
> I will set them up manually this time, but generally I don't have time to do this for everyone :-( . The optimal way is for you to only upload savegames where everything is already set up and where you know for sure that there will be an error when the AutoDrive driver goes to unload the next time.
> This way I just have to enable the helper/courseplay and enable AutoDrive on the driver and can see what's going wrong.
> With your savegame I have to do all of this manually and I don't know if this will fail/would fail on your pc.

Oh so sorry Stephan, I didnt think you required that, as I knew you probably wont of had same mods as me. are you say to use courseplay to harvest field 19 and just tractor and trailer to unload combine on AutoDrive, as I have been using mod FS19_AIVehicleExtension to harvest.  please accept my apologies

**Comment by Stephan-S** [comment] 2019-06-10 08:41
No need to aplogise :-) I have to update my version of FS19_AIVehicleExtension.
I will set it up.

**Comment by ploughedfieldman123** [comment] 2019-06-10 08:41
so do you mean its best to use course play or  FS19_AIVehicleExtension to harvest

**Comment by Stephan-S** [comment] 2019-06-10 10:42
Oh Marwell Manor sure makes it hard to use courseplay and AutoDrive.
How are you setting them up? Are you manually doing some headland rounds?
In the first round(s) the 'Field 19' destination will still be in the crop, which makes it quite hard for the driver to find a route without destroying crops :-D
Also at the first headland round, there is pretty much no space for the unloader to drive to the combine, so I am not suprised that he can't calculate a way in a reasonable time..

I bought the CR10.90 since it has a nice working width and set it up with Courseplay to harvest field 19 with 5 headland rounds.
The first unloading happened while in the middle of the first headland and the unloader starting inside the unharvested crop -> took some time and then drove through the fruit -> really to be expected in this case

Here is a new version of AutoDrive. Can you give it a try? It should be better in your marwell manor scenario: 
[FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3271706/FS19_AutoDrive.zip)

**Comment by ploughedfieldman123** [comment] 2019-06-10 10:51
> Oh Marwell Manor sure makes it hard to use courseplay and AutoDrive.
> How are you setting them up? Are you manually doing some headland rounds?
> In the first round(s) the 'Field 19' destination will still be in the crop, which makes it quite hard for the driver to find a route without destroying crops :-D
> Also at the first headland round, there is pretty much no space for the unloader to drive to the combine, so I am not suprised that he can't calculate a way in a reasonable time..
> 
> I bought the CR10.90 since it has a nice working width and set it up with Courseplay to harvest field 19 with 5 headland rounds.
> The first unloading happened while in the middle of the first headland and the unloader starting inside the unharvested crop -> took some time and then drove through the fruit -> really to be expected in this case
> 
> Here is a new version of AutoDrive. Can you give it a try? It should be better in your marwell manor scenario:
> [FS19_AutoDrive.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3271706/FS19_AutoDrive.zip)



Hi Stephan  I have that latest version of AutoDrive  v1.0.3.1  unless your version is slightly different  I got it earlier. and had tried it on field 19.  it seems a bit better.  so what do you use to harvest crops. Course Play or FS19_AIVehicleExtension

**Comment by Stephan-S** [comment] 2019-06-10 10:58
Yeah, my version is slightly different. So please give that a try first :-)
I use courseplay for such complicated fields, as it can beconfigured to do multiple headlands and it will make 'pockets' on the first headland to help the unloader with getting to it.

But even courseplay will run into some of the bushes with collision during the first headland. AIVehicleExtension had the same problem.

Personally, I never tried AIVehicleExtension a lot, so I can't say much about it, sorry

**Comment by ploughedfieldman123** [comment] 2019-06-10 11:15
Well I just tried your version, on field 19  Harvesting is on Course Play.  I set a time clock up it went to nearly 2 minutes  showing on AutoDrive menu "Drive to Combine"  nothing happened then it stopped was not green no more

**Comment by Stephan-S** [comment] 2019-06-10 11:27
And where was the combine standing in this case?
And have you removed the crop from the starting position of the unloader?

**Comment by Knowen** [comment] 2019-06-10 11:35
@Stephan-S Here is my config file for the Multimap2019. 
The selected mode was unloading combine from "Feld_08 Ablader" to "Hofsilo". 
The issue occures when the helper is finish with unloading the combine and wants to go to the parking location or generally wants to reach that spot. I think the easiest way to reproduce ist to be on the street between field 8 and 9 heading east and just say drive to "Feld_08 Ablader". 


[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3271853/AutoDrive_Multimap_2019_config.zip)

**Comment by ploughedfieldman123** [comment] 2019-06-10 11:59
> And where was the combine standing in this case?
> And have you removed the crop from the starting position of the unloader?

I forgot to take a screenshot of combine but it wasn't very far away. also yes there was still crop where tractor and trailer stood. so when i removed crop from where tractor and trailer was tried again it was just 1 minute when tractor went to unload combine so its getting better. I will play about with this on another field see how it goes will let you know

**Comment by Stephan-S** [comment] 2019-06-10 13:07
I really don't know what you are doing @ploughedfieldman123 When I set this up the driver starts in a matter of seconds if there is a crop free path available. If not it will of course take longer

**Comment by Stephan-S** [comment] 2019-06-10 13:20
@Knowen Thanks for uploading your config.
I've tried it and yeah it would take the 'wrong' way with your config.
But then I switched to 'use fastest route' : No and recaclulated it (which is now always available since 1.0.3.1) and voilá it takes the expected route.
Here is the newly calculated config with nothing else changed but the above mentioned setting:
[AutoDrive_Multimap_2019_config.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3272172/AutoDrive_Multimap_2019_config.zip)

**Comment by ploughedfieldman123** [comment] 2019-06-10 13:21
what do you mean a crop free path

**Comment by Stephan-S** [comment] 2019-06-10 13:23
well it tries to avoid crop/fruit, so any wheat, barley etc, that is on the field. It will try to only drive on already harvested parts of the field.

**Comment by ploughedfieldman123** [comment] 2019-06-10 14:33
> well it tries to avoid crop/fruit, so any wheat, barley etc, that is on the field. It will try to only drive on already harvested parts of the field.

so what you are saying then make sure there is no crops where tractor and trailer waits to drive to combine to unload, as earlier the tractor crossed over field which was full of crops

**Comment by Knowen** [comment] 2019-06-11 06:14
@Stephan-S yeah it works fine now. 👍 
but i allready tried this steps. i recalculated everything and switched "Fastest route" from yes to no and back. i think it is black magic 😄

**Comment by ploughedfieldman123** [comment] 2019-06-11 08:46
How can you message someone here as I want to ask Knowen a question, or do i put question here

**Comment by Knowen** [comment] 2019-06-11 09:23
@ploughedfieldman123 Just ask me here 😄

**Comment by Bobster82** [comment] 2019-06-11 09:31
@ploughedfieldman123  ... type the @ symbol, then the name appears who u want to tag, select it and he or she gets a notice

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:33
Hi Knowen, I just looked at your config file with your map, how do you make that field 15 as it just stops at field 15 I thought you are supposed to link the lines up to work, also how do you make those straight lines very nice I cant

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:33
@Bobster82  like this you mean

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:35
it cant be working Bobster82  as had no answer

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:41
can you not get me Knowen or even Bobster82  as no 1 is replying

**Comment by Bobster82** [comment] 2019-06-11 09:42
@ploughedfieldman123 , Oo, you mean a private message?? You cant send a private msg as ive know of... I see that u tagged me ;)

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:43
> @ploughedfieldman123 , Oo, you mean a private message?? You cant send a private msg as ive know of... I see that u tagged me ;)

no here will do not a problem. But Knowen  just replied but dont anymore so I am a bit confused

**Comment by Bobster82** [comment] 2019-06-11 09:46
Some people have other things to do ;) they just check every now and then if there is something new.... Its not a chat box :P ... have a great day, I need to do something else too

**Comment by ploughedfieldman123** [comment] 2019-06-11 09:47
> Some people have other things to do ;) they just check every now and then if there is something new.... Its not a chat box :P ... have a great day, I need to do something else too

Well yes so do i have other things to do, but person just replied i asked what I wanted to ask but no more reply, its ok I will check up next time

**Comment by Knowen** [comment] 2019-06-11 10:18
@ploughedfieldman123 Sorry, was a little bit bussy.
For every field i have two destintions. One for the driver who unloads my combine and one, the one you mean, as a dead end for any vehicle i want to work on that field. 
With this setup i can have an active combine with an unload-driver  and can also send the next needed machine to the field without disturbing the unload-driver. 

If i want to send someone to the dead end i simple set the mode on "drive" and select the dead end location "field 15" in this case. Once the driver reach the destination i get a message from AD that the driver reached the destination.

**Comment by ploughedfieldman123** [comment] 2019-06-11 10:36
> @ploughedfieldman123 Sorry, was a little bit bussy.
> For every field i have two destintions. One for the driver who unloads my combine and one, the one you mean, as a dead end for any vehicle i want to work on that field.
> With this setup i can have an active combine with an unload-driver and can also send the next needed machine to the field without disturbing the unload-driver.
> 
> If i want to send someone to the dead end i simple set the mode on "drive" and select the dead end location "field 15" in this case. Once the driver reach the destination i get a message from AD that the driver reached the destination.
> 
> PS: I think it isn't possible to send someone a PM.

Oh as I just thought all the arrows had to be linked up.  I didn't realise you could do that.  will try next time

also how do you manage to make very straight lines LOL, as I play on Marwell Manor map. but when I make the routes I do it in the game by driving along road, but its not staright like yours as I have to move into middle of road as if not trailer hits road signs

**Comment by Knowen** [comment] 2019-06-11 10:44
> 
> 
> > @ploughedfieldman123 Sorry, was a little bit bussy.
> > For every field i have two destintions. One for the driver who unloads my combine and one, the one you mean, as a dead end for any vehicle i want to work on that field.
> > With this setup i can have an active combine with an unload-driver and can also send the next needed machine to the field without disturbing the unload-driver.
> > If i want to send someone to the dead end i simple set the mode on "drive" and select the dead end location "field 15" in this case. Once the driver reach the destination i get a message from AD that the driver reached the destination.
> > PS: I think it isn't possible to send someone a PM.
> 
> Oh as I just thought all the arrows had to be linked up. I didn't realise you could do that. will try next time
> 
> also how do you manage to make very straight lines LOL, as I play on Marwell Manor map. but when I make the routes I do it in the game by driving along road, but its not straight like yours as I have to move into middle of road as if not trailer hits road signs

The most of my lines aren't straigt when i record them in game. If i see a problem (collison or not enugh space between the lines on a road) i edit the course with the AD Editor.

**Comment by ploughedfieldman123** [comment] 2019-06-11 12:16
yes I do that too. I will mark the waypoints with a set of numbers so I can locate them easier in the editor

**Comment by ploughedfieldman123** [comment] 2019-06-13 10:08
@Knowen  hi you about

**Closed** 2019-08-27 13:40 UTC
