### ISSUE TITLE
slow driving

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#907] opened 2019-11-20 12:40 UTC
I have latest version of AutoDrive 1.0.6.9

But how comes when you link up 2 routes in Courseplay  1 from AD  the 2nd from  CP  so it says 2 combined routes. but it will only drive at 6 MPH   I have also checked in CP  tab where speed shows and it cant be changed. I hope someone can help here  

<a href="https://ibb.co/bKgW0qh"><img src="https://i.ibb.co/FDbxrNv/2019-11-20-123428.jpg" alt="2019-11-20-123428" border="0"></a><br />

<a href="https://imgbb.com/"><img src="https://i.ibb.co/n1ZcnVS/2019-11-20-123733.jpg" alt="2019-11-20-123733" border="0"></a><br />

**Comment by Michael170978** [comment] 2019-11-20 14:01
Please check the speed of your cruise control.

**Comment by ploughedfieldman123** [comment] 2019-11-20 15:34
> Please check the speed of your cruise control.

Where is cruise control

**Comment by Roby1164** [comment] 2019-11-20 15:56
> > Please check the speed of your cruise control.
> 
> As you can see cruise control is on highest it can go 22 MPH but tractor only drives at 6 MPH
> 
> [![2019-11-20-154605](https://camo.githubusercontent.com/cd69b5f0cae803562edbea470c8574b44f51fe7f/68747470733a2f2f692e6962622e636f2f4d50746273686b2f323031392d31312d32302d3135343630352e6a7067)](https://ibb.co/DwvNtbf)

It is true that the vehicle can go to 22 per hour, but you have the vehicle set at 6 km / h, as you can see in the number I highlighted
![Screenshot_3](https://user-images.githubusercontent.com/24955554/69254576-c11bcf00-0bb6-11ea-8164-e4a5a4753ef0.jpg)

**Comment by ploughedfieldman123** [comment] 2019-11-20 16:02
> > > Please check the speed of your cruise control.
> > 
> > 
> > As you can see cruise control is on highest it can go 22 MPH but tractor only drives at 6 MPH
> > [![2019-11-20-154605](https://camo.githubusercontent.com/cd69b5f0cae803562edbea470c8574b44f51fe7f/68747470733a2f2f692e6962622e636f2f4d50746273686b2f323031392d31312d32302d3135343630352e6a7067)](https://ibb.co/DwvNtbf)
> 
> It is true that the vehicle can go to 22 per hour, but you have the vehicle set at 6 km / h, as you can see in the number I highlighted
> ![Screenshot_3](https://user-images.githubusercontent.com/24955554/69254576-c11bcf00-0bb6-11ea-8164-e4a5a4753ef0.jpg)

But I cant see anywhere I have set it to 6 MPH where do I increase it then

**Comment by Roby1164** [comment] 2019-11-20 16:22
Key 2 on the keyboard, when you are on the vehicle and AD or CP deactivated.

**Comment by ploughedfieldman123** [comment] 2019-11-20 16:41
> Key 2 on the keyboard, when you are on the vehicle and AD or CP deactivated.

Wow I can see now it increases speed.  when I unattached the trailer. in the F1 menu. I had tried  hitting 1 and 2 numbers but didn't look at near speed dial.

many thanks for that 

<a href="https://ibb.co/NWcLLgv"><img src="https://i.ibb.co/JrDzzW1/2019-11-20-163756.jpg" alt="2019-11-20-163756" border="0"></a>

**Comment by Trigger87** [comment] 2019-11-20 17:59
I have the same problem with slow driving tractors with trailers.

My tractors delivers from the field to the BGA. While unloading the trailer into the BGA my tractor drives 16kmh and after unloading the speed remains at 16kmh. The speed doesnt go up again until i save the game and reload it.

This bug is reproduceable. Let AD drive to the BGA and let it automatically unload the trailer. It happens every time.

Have a nice day :)

**Comment by GitTomahawk** [comment] 2019-11-24 14:47
I've noticed the same issue in release 1.0.6.9 but it seems to be fixed in current dev. Version (14).
Running Release Version it even appears if one driver just drives through a fahrsilo on the way to its unloading target.

**Comment by Stephan-S** [comment] 2019-11-25 17:17
Yeah the speed after unloading into bunker silos should be fixed. So I'll close this issue for now :-)

**Closed by Stephan-S** 2019-11-25 17:17 UTC
Labels: further-investigations
