### ISSUE TITLE
AD Drivers wait for each other

### ISSUE THREAD

**Issue by Martinnygaard** [Stephan-S/FS19_AutoDrive#926] opened 2019-11-23 14:50 UTC
AutoDrive Version: 1.0.6.9-12
Release or custom zip: Custom Zip
Map (if applicable): Fenton Forrest x4
Vehicle / type (applicable): Vanilla Case IH tractors / harvesters

**Describe the bug**
I've seen this issue many times during my use of AD.

When multiple drivers are using the same part of the route, and come to close to each other, they will stop and wait for the route to be free. 

The problem is in this (extreme) case, 3 drivers are travelling the same way. 

Therefore only the second and last driver should wait, if they gets too close to the leading vehicle.
In this case, the leading vehicle is also waiting, even when there is no driver in front of him.

When i turn off AD in the 2nd and 3rd tractor, the leading does not detect other drivers anymore, and continue.

This results in an infinite waiting loop until i turn off AD on the trailing vehicles.

**If applicable - Steps to reproduce the behavior**
Run mulitple AD close together on the same route. 
Have happend many times for me.

**Screenshots**
![AD Waiting](https://user-images.githubusercontent.com/26490587/69480572-ddaf4580-0e08-11ea-9160-64d5e5a32ef6.png)

**Comment by Iwan1803** [comment] 2019-11-23 16:57
Why the first one has stopped and is blocking the route?
If road is blocked, what should the 2nd and 3rd do?

**Comment by Martinnygaard** [comment] 2019-11-23 17:10
The first is strangly waiting on the 2nd and 3rd that is behind it.

So all three wits on eachother.

**Comment by Martinnygaard** [comment] 2019-11-23 20:24
Again in a completely straight line.

When i turn off AD in the rear tractor, the front starts running again.

![image](https://user-images.githubusercontent.com/26490587/69484762-6e047f00-0e37-11ea-94cc-1a746a36733d.png)

**Comment by Stephan-S** [comment] 2019-11-24 09:13
I'm on it. That is happening since I allowed traffic going in the same direction on a blue path to drive on this section at the same time.
Now when leaving the blue track, the first vehicle is still checking if he is allowed to enter/blocking the entrance to the blue section, which was previously used to delay the entry of opposing traffic for a few waypoints but should no longer be needed in this case

**Comment by wallsingham** [comment] 2019-11-24 09:17
@Stephan-S : Exactly
I can confirm also this behavior. It always happens when two or more vehicles arrive in series at the exit of "2-way" routes. Then the first vehicle stops at the exit of the "2-way" route.
When manually turning off AD at the second vehicle, the first vehicle then continues driving.

**Comment by Stephan-S** [comment] 2019-11-25 16:47
I included a fix for this in the 1.0.7.0 release.
If this issue is still present or there are other issues with the entry/exit of dual way routes now, please reopen this issue. Thank you

**Closed by Stephan-S** 2019-11-25 16:47 UTC
Labels: further-investigations
