### ISSUE TITLE
Park spot isnt always correct

### ISSUE THREAD

**Issue by Bobster82** [Stephan-S/FS19_AutoDrive#401] opened 2019-08-23 14:44 UTC
Hi,

When i assign vehicles to a Park possition it isnt always the same as I registered.
I dont know if its when I come back to my save game or just when I play

I Found it out earlier, but thought I clicked wrong :P 
But now its more often, I had a lot of vehicles assigned to their spots, but pressing Park now wont get the vehicle to his destination (what i registered), just a random (or the previous destination where he went to)

**Comment by aviator64** [comment] 2019-08-26 05:24
After you assigned the parking spots, did you edit your course and add or remove destinations?

Each vehicle's parking destination is saved as a map marker number. When you add or delete destinations the map marker numbering will change and it is possible that a particular number will then refer to a different destination.

Stephan - does this sound reasonable? Any way to save parking locations by name instead of number?

**Comment by Bobster82** [comment] 2019-08-26 15:54
@aviator64 , no I didnt changed the route ;)
About the Numbers, they should always stay the same, your destinations never change? or do they? :P 
I think the parking spots needs to be hardcoded, the same as destinations are. I dont know how the parking function is coded, but I cant see them in the xml
Maybe @Stephan-S can work around it and hardcode them, the same way as destinations are?

**Comment by Stephan-S** [comment] 2019-08-26 16:09
Hey,
@aviator64 is right. When you assign a parking spot, it internally stores the current id of that destination as parking spot.
When you delete destinations in your network, these ids will change to keep them consecutive.

I then forgot to adjust the park destinations ids as well. Will be fixed in the next release!
At least that is for now the only explanation I have. If you tell me you definitely haven't changed the network since assigning the parking spots, I will have to look deeper for some bugs.

Best regards,
Stephan

**Comment by Stephan-S** [comment] 2019-08-26 16:10
Oh and @aviator64, if I store them by name, I will have to go through the same process when you rename the destinations, which is now possible by right/middle mouse clicking on 'Create Destination' :-)

**Comment by Bobster82** [comment] 2019-08-26 16:13
I just started the savegame again after I parked all the tractors, then i press park and its going somewhere else ;)
I tried changing some stuff around, then the park still be the same ... I cant debug it, so i dont know whats happening.


Youre great stephan, thanks!

**Comment by Bobster82** [comment] 2019-08-26 16:41
@Stephan-S , btw... when a vehicle is parked, the engine keeps running... can that be solved easy?

**Comment by aviator64** [comment] 2019-08-27 05:18
> Oh and @aviator64, if I store them by name, I will have to go through the same process when you rename the destinations, which is now possible by right/middle mouse clicking on 'Create Destination' :-)

I just thought saving by name might be easier than adjusting the parking IDs when destinations are added/deleted. If you are going to update the parking IDs that will certainly work :-)

**Comment by aviator64** [comment] 2019-08-27 05:33
@Bobster82 the parking locations are in your savegame's vehicles.xml file, each vehicle has an autodrive section.

**Comment by Bobster82** [comment] 2019-08-27 07:42
Thanks. Will have a look into that and see if I can find any usefull for me

**Closed** 2019-08-27 13:56 UTC

**Comment by Bobster82** [comment] 2019-08-28 10:40
@Stephan-S , I deleted a waypoint name and added a new one, then the parkingspots where messed up again... the changes didnt work ;)

**Comment by Stephan-S** [comment] 2019-08-28 11:12
works perfectly fine on my tests.
Could you tell me exactly which steps you take to reproduce this?
I can delete waypoints, destinations and create new ones as much as I like. If I send him to the parking spot, he always choses the set one.

**Comment by Stephan-S** [comment] 2019-08-28 11:15
Ok, found the error. Thanks

**Comment by Bobster82** [comment] 2019-08-28 11:16
lol, just wanted to tell my story. haha,. thx

**Comment by Stephan-S** [comment] 2019-08-28 14:42
New fix is online :-)

**Comment by Bobster82** [comment] 2019-09-11 18:54
@Stephan-S , Hi, sorry I didnt test it earlier, didnt had much time to play
The parking spots are gone when i save the game and come back at a later time... So I need to asign them again every time I load the game

**Comment by Bobster82** [comment] 2019-09-13 12:52
Maybe I did something wrong, but saw some strange numbers in vehicle.xml saw parkdestination=-2 ?
But later i assigned every vehicle again, and saw in the xml that the numbers where equal to the destination... So I dont know what went wrong, but will post again if I see something strange ;)
