### ISSUE TITLE
Abfahrer Fährt immer zu dicht auf und Bremst Ab[BUG]

### ISSUE THREAD

**Issue by BlackStar153** [Stephan-S/FS19_AutoDrive#1879] opened 2021-04-11 09:08 UTC
**AutoDrive Version:** 1.1.0.9-RC1
**Release or Custom Zip:** Release  
**Map (If applicable):** Steffenhausen
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
Das problem is deas der Abfahrer immer zu dicht auf Fährt und auch die einstellungen Ignoriert dadruch fährt er immer an fährt denn Hächsler zu dicht auf und Bremst wieder ab und das immer wieder. In denn Einstellung was denn Abstand an geht kann ich einstellen was ich will das ändert nichts.

**If applicable - Steps to reproduce the behavior**  

**Screenshots**  
![20210411110453_1](https://user-images.githubusercontent.com/79724679/114298301-f8459580-9ab5-11eb-9b0a-3b07d28a3056.jpg)

**Comment by Iwan1803** [comment] 2021-04-11 21:45
Ich vermute mal, du meinst "Steffishausen" und du solltest es mal mit Vanilla-Fahrzeugen (ohne Frontanbauten) probieren.

**Comment by BlackStar153** [comment] 2021-04-12 16:54
das sind vanila fahrzeuge und der trecker hat kein frontanbau

**Comment by Axel32019** [comment] 2021-04-12 18:00
Häcksler mit langem Entladerohr? 3m Abstand sollte gut funktionieren.

**Comment by BlackStar153** [comment] 2021-04-14 17:24
@Axel32019 jap das is der Standart hächsler mit langen Pipline

es ist egal welchen abstand ich einstelle der abfahrer übernimmt den abstand leider nicht

**Comment by Axel32019** [comment] 2021-04-14 18:19
@jala15 Could this be a side-effect of the last changes via PR?

**Comment by jala15** [comment] 2021-04-14 18:35
It shouldn't but anyway: 
What is your setting in Experimental Features > dynamicChaseDistance? Please change it and try again

**Comment by BlackStar153** [comment] 2021-04-15 17:17
ging die ausage an mich?

**Comment by jala15** [comment] 2021-04-15 17:21
Yes

**Comment by BlackStar153** [comment] 2021-04-16 19:15
i tried to adjust the distance several times and that doesn't change anything the downhill rider keeps on going because havister opens

**Comment by jala15** [comment] 2021-04-18 16:20
Then this is not caused by the last changes but I will try to reproduce it and find what is happening. Vanilla Krone with grass pick up driven by CP I guess. 
@BlackStar153 Do you know any previous working version?

**Comment by jala15** [comment] 2021-04-20 22:51
Unloader stops because of forage harvester stopping because it gets too far away in a loop. This should at least partly fix this issue. I could not manage to get grass detected as fruit so I had to test with direct disc and wheat. This is slower (15km/h) than the pick up (20km/h) so @BlackStar153  please tell me if the issue is already there. The distance adjustment works as it should. 0 m = The rear bumper of the harvester but sometimes it triggers a collision and stops.
@Axel32019 Sometimes the front collision is triggered but not always, here are three pics of the black/orange box

Before reaching:
![vlcsnap-2021-04-21-00h47m56s859](https://user-images.githubusercontent.com/52028079/115473127-71be5000-a23b-11eb-8da2-aec4c9483e90.png)

Triggered:
![vlcsnap-2021-04-21-00h47m39s621](https://user-images.githubusercontent.com/52028079/115473145-784cc780-a23b-11eb-80b8-4213c8b63150.png)

Not triggered:
![vlcsnap-2021-04-21-00h48m46s879](https://user-images.githubusercontent.com/52028079/115473158-7d117b80-a23b-11eb-8a26-546e5b3ae771.png)

**Comment by BlackStar153** [comment] 2021-04-21 16:07
don't understand exactly what you want from me?

**Comment by jala15** [comment] 2021-04-22 18:57
> don't understand exactly what you want from me?

I don't have write access to this repository so I can't merge pull requests.
As soon as @Axel32019 gets #1893 merged I want you to test it, but you can't do anything yet

**Comment by Axel32019** [comment] 2021-04-24 14:58
@BlackStar153 , @jala15 From my understanding the collision detection is not the issue here, as it is deactivated in function call:
``self.vehicle.ad.specialDrivingModule:driveToPoint(dt,` self.chasePos, combineSpeed, false, acc, `totalSpeedLimit)``
I would say the root cause is the discharge node of the trailer, which is too far behind and the delay until harvester and unloader accelerate.
This might lead the harvest disappear from discharge node of the trailer before unloader is following -> cyclc...
I will have a look at the PR...

**Comment by jala15** [comment] 2021-04-24 16:17
Collision detection is not fully deactivated. You can see the front box going orange and just then the tractor stops. `self.vehicle.ad.sensors.frontSensor:pollInfo()` is triggered and makes unloader stop.
https://github.com/Stephan-S/FS19_AutoDrive/blob/bf9e40a6775f899bb657892820195f1e203a46ac/FS19_AutoDrive/scripts/Modules/SpecialDrivingModule.lua#L146
I would change it myself to `if checkDynamicCollision and (self.vehicle.ad.collisionDetectionModule:hasDetectedObstable(dt) or self.vehicle.ad.sensors.frontSensor:pollInfo()) then ` but I'm not sure if it would have any unwanted behaviour.

**Comment by Axel32019** [comment] 2021-04-24 16:41
You are right - too many brackets! Your change looks promising.

**Comment by Axel32019** [comment] 2021-04-24 18:41
I changed the collision check as suggested - you may test in beta already

**Comment by BlackStar153** [comment] 2021-04-25 10:45
@Axel32019  ich werde es mal testen :) Danke erst mal für die mühe

**Closed** 2021-06-05 21:35 UTC
Labels: bug
