### ISSUE TITLE
AD Driver does not stop engine

### ISSUE THREAD

**Issue by RUGhost** [Stephan-S/FS19_AutoDrive#272] opened 2019-07-05 13:56 UTC
AD driver does not stop Engine after completing task. After reached the destination point he just left away without stopping engine.

**Comment by aviator64** [comment] 2019-07-05 17:40
Yes I have seen this too, you have to tab into the vehicle and tab out again to make the engine stop.

I have auto engine start enabled, don't know if that makes a difference.

**Comment by Gariot** [comment] 2019-07-06 10:53
Duplicate of #93

**Closed** 2019-07-06 13:59 UTC
