### ISSUE TITLE
unload crops

### ISSUE THREAD

**Issue by ploughedfieldman123** [Stephan-S/FS19_AutoDrive#37] opened 2019-04-09 07:59 UTC
I still cannot see how to unload crops at triggers etc. can someone explain how

**Comment by Stephan-S** [comment] 2019-04-10 19:33
Duplicate of #31 
Please have a look at Ians Channel, which was provided to you in #31 
If then there are any concrete questions left, feel free to ask them.

**Closed by Stephan-S** 2019-04-10 19:33 UTC
