### ISSUE TITLE
[BUG] Global Company can't be opened

### ISSUE THREAD

**Issue by BillyElliott78** [Stephan-S/FS19_AutoDrive#1978] opened 2021-06-17 22:33 UTC
**AutoDrive Version:** 1.1.1.2   
**Release or Custom Zip:** Release  
**Map (If applicable):** PV County 
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

**Describe the bug**  
since updating to the latest version of AutoDrive i keep loosing the option to open Global Company Menu with the R key and i seem to get this in my log

Info: [AD] Info: g_server table: 0x022a2db59af0 g_client table: 0x022a2da61988 g_dedicatedServerInfo nil getUserProfileAppPath C:/Users/Owner/Documents/My Games/FarmingSimulator2019/ getIsClient true getIsServer true isMasterUser true

**If applicable - Steps to reproduce the behavior**  
It seem to happen as soon as i load into my savegame.

**Screenshots**  

Normally it shows in the F1 menu R Key to open Global Company Menu but nothings showing

https://drive.google.com/file/d/1uv26_Rc0LSTRVL8gPTcec1mF8zoUMbz6/view?usp=sharing

**Comment by Iwan1803** [comment] 2021-06-18 05:43
The line starting with "Info" ist only a info line as it says.
I use also GC and i don't have this problem.
Was something else changed on this savegame?
Please attach the log so that we can check this.

**Comment by BillyElliott78** [comment] 2021-06-18 08:26
so this is my last game log 

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/6675725/log.txt)

**Comment by Dzi4d3k** [comment] 2021-06-18 08:40
And what for is LCTRL+G used in you screenshoot? Also as far As I remember R is for opening shop menu not GC.

**Comment by BillyElliott78** [comment] 2021-06-18 08:49
R key is for opening global company menus as well as a few other trigger like the shop. One of the storage buildings used on PV County has items in it that doesn't show in the normal global company menu so you have to go to the trigger and press the R key to see the products and amounts stored. But since updating to the latest version from GitHub I can access these menus as my R key options somehow been affected

**Comment by jala15** [comment] 2021-06-18 09:31
Now that I see this issue, I have also experienced this. 'R' key sometimes gets blocked so I can't manage my animals or any other action activated by 'R'. It doesn't happen always and (I'm not sure) I kind of remember 'R' key re-enabling when entering and exiting a tractor.
It might be caused by AD starting to refill from a silo (R key), but I have not done further tests. Maybe AD refilling while the player is not in a vehicle?

**Comment by Mannie313** [comment] 2021-06-18 09:54
Dies passieret wen man in einem GC trigger ist und aus dem Fahrzeug tabbt. 
Und ich spiele auch mit GC

MFG Mannie313

**Comment by BillyElliott78** [comment] 2021-06-18 10:09
I alway walk away from the triggers before tabbing to a vehicle, plus it affected another of my mods that I had no issues with before the update. The player speed mod uses the B key to increase the players walking speed and is deactivate within moments of loading the savegame.

**Comment by Iwan1803** [comment] 2021-06-18 11:43
Pressing 'R' opens something at a trigger you are at. LCTRL + G opens GC directly.
The bug with pressing 'R' and GC opens instead of f.e. the menu to manage animals is known.
This is not caused by AD.

**Comment by BillyElliott78** [comment] 2021-06-18 11:56
Just seems strange the for a long time I've never had a issue then as soon as I update 1 thing I start having problems. Tbh I'm removing autodrive and probably won't be using it again. 😞

**Comment by BillyElliott78** [comment] 2021-06-18 12:56
So I removed autodrive and all the previous issues have now gone so there's definitely something in the current version that's affecting other mods being used so I'm going to keep it out of my game.

**Comment by Iwan1803** [comment] 2021-06-18 13:10
Ok, so there is no need for further investigations and i'll close this issue.

**Closed by Iwan1803** 2021-06-18 13:10 UTC
Labels: bug

**Comment by Mannie313** [comment] 2021-06-18 13:50
Ich weiß nicht warum alle es immer auf AD, CP oder GC schieben wen was net geht. einfach mal den mods ordner aufräumen und dann geht alles wieder. ich hab alle drei AD, CP und GC drin alles läuft wie es soll.

**Comment by BillyElliott78** [comment] 2021-06-18 14:43
All my mods are clean and have run without issue untill now. If you don't have something positive to add don't comment

**Comment by Gibbanator** [comment] 2021-06-18 14:58
when you put in a problem or complaint it is not a positive statement so by definition you cant be positive all the time
