### ISSUE TITLE
Overloading to multi bay trailers (Wilson)

### ISSUE THREAD

**Issue by WrinkleysRule** [Stephan-S/FS19_AutoDrive#1625] opened 2020-10-14 11:03 UTC
Overloading to Multi bay trailers (Wilson) Single Player
Versions: 1.1.0.4 and 1.1.0.5-RC6
Map: Ravenport
 When using Autodrive to carry out this task it only discharges into rear bin misses front bin completely. If target moved forward slightly then only fills front bin and will not continue to rear bin if auger wagon not completely empty.
No problems when using same trailer when filling or dumping at main silo.
No errors in log and only AutoDrive  in the mods folder folllowing  are the Auotodrive entries in the log 

2020-10-14 11:31   Load mod: FS19_AutoDrive
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "selfPropelledSprayer"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "tractor"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "baseDrivable"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "loaderVehicle"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "woodTruck"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "cottonHarvester"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "drivableMixerWagon"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "conveyorBelt"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "tractorCrabSteering"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "pickupConveyorBelt"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "carFillable"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "teleHandler"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "tractorReverseDriving"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "woodCrusherTrailerDrivable"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "combineCutterFruitPreparer"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "woodHarvester"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "selfPropelledMower"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "forwarder"
2020-10-14 11:31   Info: [AutoDrive] Attached to vehicleType "combineDrivable"

2020-10-14 11:31   Info: [AD] Start register later loaded mods...
2020-10-14 11:31   Info: [AD] Start register later loaded mods end
2020-10-14 11:31   Info: [AD] AutoDrive.readFromXML waypoints: 310
2020-10-14 11:31   Info: [AD] AutoDrive.readFromXML markers: 7
2020-10-14 11:31   Info: [AD] AutoDrive.readFromXML groups: 1
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/line.i3d (0.31 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/arrow.i3d (0.16 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/sphere_small.i3d (0.13 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/sphere.i3d (0.19 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/marker.i3d (3.74 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/marker_2.i3d (3.31 ms)
2020-10-14 11:31 D:/GAMES/mods/FS19_AutoDrive/drawing/marker_3.i3d (5.50 ms)
2020-10-14 11:31   Info: [AutoDrive] Loaded mod version 1.1.0.5 (by Stephan). Full version number: 1.1.0.5-RC6

**Comment by rohne83** [comment] 2020-10-15 18:52
sounds like a duplicate of https://github.com/Stephan-S/FS19_AutoDrive/issues/1609 to me?

**Comment by WrinkleysRule** [comment] 2020-10-15 20:04
No that is using two separate trailers a distance apart, the Wilson Trailer has two separate bins whose independent triggers are a lot closer together (within 1m) in one trailer body.

________________________________

**Comment by rohne83** [comment] 2020-10-15 21:00
But from technical point of view there's no real difference. You have several fillUnits and want the auger wagon to unload into all of these. There are mods for the Wilson trailer with a hitch, so you can make it a road train, and have even more fillUnits, two in the same trailer, two in the next, and so on. And it would still be the same requirement.
But atm auger wagons only unload into the first. Same issue with Courseplay (which I prefer for this kind of work).

**Comment by WrinkleysRule** [comment] 2020-10-16 08:40
No, I disagree, the problem in #1609 refers to unloading into multiple connected trailers each having their own independent identity and fill level/trigger not a single connected trailer with multiple fill sections, one identity and one fill capacity but split into two separate bins.
There seems to be a reference to the problem here
https://github.com/Stephan-S/FS19_AutoDrive/commit/72b5d8031d8f82dd6a54313c9e0c8e2dd6bacfd9
Regarding the same issue you say you have with Courseplay perhaps this video might help
https://www.youtube.com/watch?v=42WTOyw12KM

________________________________

**Comment by Axel32019** [comment] 2020-12-27 09:18
@WrinkleysRule @rohne83 Hello,
First implementation is in beta branch - if you want to try see how to: #1663

**Comment by envikowaty** [comment] 2021-01-07 21:03
> @WrinkleysRule @rohne83 Hello,
> 
> First implementation is in beta branch - if you want to try see how to: #1663

So @Axel32019 It's better now ? Any progress ?

**Comment by Axel32019** [comment] 2021-01-07 21:21
@envikowaty Yes, but only available in beta version!

**Comment by envikowaty** [comment] 2021-01-08 10:48
> @envikowaty Yes, but only available in beta version!

Ok ! I will ran some tests

**Comment by Axel32019** [comment] 2021-03-03 18:33
No further info / update -> closed

**Closed by Axel32019** 2021-03-03 18:33 UTC
Labels: bug
