### ISSUE TITLE
Stop searching - no path found in reasonable time / Autodrive hat ein Problem beim Initialisieren festgestellt

### ISSUE THREAD

**Issue by Scaracuila** [Stephan-S/FS19_AutoDrive#61] opened 2019-04-13 12:42 UTC
Hi,

erst mal vielen Dank, dass du den AD für LS19 weitermachst!!!

Ich setze AD auf der Kandelin ein (Multiplayer) und erprobe gerade den neuen Modus "Drescher abfahren".
Ich habe auf einem Dualkurs (der blaue) einen Wegpunkt für ein Feld gesetzt und diesen auch beim Drescher eingestellt. Der Abfaherer gibt mir dann den den Fehler: 
Stop searching - no path found in reasonable time / Autodrive hat ein Problem beim Initialisieren festgestellt
Liegt es daran, dass die Wegpunkte von Dualen Kursen nicht im Kombimodus funktionieren?
Habe den Drescher mit CP (habe ich für MP freigegeben) im Feldarbeitsmodus und auch mit normalem Helfer laufen lassen.

Hier mal meine Log:
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3076170/log.txt)

Nach 3-4 dieser Meldungen deaktiviert sich der Abfahrer.

Vielen Dank schon mal für deine Hilfe!

Hi,

first of all thank you very much for continuing the AD for LS19!!!

I'm using AD on the Kandelin (Multiplayer) and trying out the new combine mode.
I set a waypoint for a field on a dual course (the blue one) and also set it on the combine. The driver gives me the error: 
Stop searching - no path found in reasonable time / Autodrive detected a problem during initialization
Is it because the waypoints of Dual Courses do not work in combined mode?
I have run the combine with CP (I have enabled CP for MP)  in fieldwork mode and also with normal helper.

After 3-4 of these messages the driver deactivates himself.

Thank you very much for your help!

**Comment by Stephan-S** [comment] 2019-04-13 12:54
Hey, I don't think it has something to do with the dual roads at that point.
There could be two reasons I can think of right now. First, how far is the distance between the combine and the driver? There is a limit in the calculation steps which I reduced maybe a little to much, so the driver might not be able to find a route in time.
The next thing is in regard to the errors in your log file. I don't think they are related to AutoDrive, but there the 'ground terrain detail' is different from the default maps and I haven't tested this yet. So he might not find a route that avoids fruit, but he should never the less find a route.
To test if the distance is a problem, just drive the combine closer and then unfold the pipe (combine at 100% fill level). If that does not help, I will increase the allowed path finding steps with the next release and also add a keybinding to call the driver manually (pipe already unfolded).

If it doesn't help, I could use your savegame to debug the problem.

**Comment by Scaracuila** [comment] 2019-04-13 13:45
Thank you very much for your quick answer!

The combine was already quite far away, I think it was more than 200m.Now I put the combine closer to the driver, but I get the same error.

The error with ´ground terrain detail´ comes from CP in combination with the map, in the map some resolutions are too high for CP - but should be fixed at the next mapupdate, but other place and topic...

Now I created a new point on the field and positioned the combine in throwing distance with active helper, I also get the same error there.

Here is a screenshot and after restart a log without CP error.
![fsScreen_2019_04_13_15_30_33](https://user-images.githubusercontent.com/34663971/56080516-63462e00-5e02-11e9-89ba-67dac9d486ef.png)
[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3076266/log.txt)

**Comment by Scaracuila** [comment] 2019-04-13 14:01
and my Savegame if you need it...
[savegame Kandelin Issue #61.zip](https://github.com/Stephan-S/FS19_AutoDrive/files/3076272/savegame.Kandelin.Issue.61.zip)

**Comment by Stephan-S** [comment] 2019-04-13 14:16
Thanks for providing the infos so quick. I will have a look at it.
Might be caused by the same issue as the CP bug though. Since AD also queries the field info to find fruit free paths.
I'm downloading the map right now and will keep you updated.

**Comment by Scaracuila** [comment] 2019-04-14 08:50
Hi, I once searched out the issue concerning the problems of CP and the Map Kandelin, maybe this is a clue for you.
https://github.com/Courseplay/courseplay/issues/3503
Thanks a lot!

**Comment by Stephan-S** [comment] 2019-04-21 21:57
Should be fixed with latest release

**Closed by Stephan-S** 2019-04-21 21:57 UTC
