### ISSUE TITLE
autodrive freezes camera

### ISSUE THREAD

**Issue by roddipoddi** [Stephan-S/FS19_AutoDrive#526] opened 2019-09-24 18:51 UTC
it's kind of a weird problem i have and to be honest i'm not 100% sure if it is an autodrive issue, my log says it though.

the problem is: sometimes (not all the time!) i can't move the camera with my keyboard. it moves when i move the mouse and usually i can move the camera with the keyboard again. i can't say when the problem occurs but suddenly it just appears. and usually a few minutes after it appeared the first time i get this error in my log and the camera is spinning around wildly:

> Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDrive.lua:475: attempt to index local 'spec' (a nil value)
> 2019-09-24 20:40 Error: Running LUA method 'update'.

does anyone have a clue or is experiencing the same problem?
any known mod conflicts? i'm pretty new to autodrive and i think the problem occured the first time after installing autodrive. i though it might be because i changed the input bindings for the autodrive menu but even after deleting the inputbinding.xml, resetting the controls ingame and even de- and re-installing fs19 didn't solve the problem.

log is attached.

[log.txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3648901/log.txt)

**Comment by aviator64** [comment] 2019-09-26 01:39
This started happening when AD started to share the mouse with Courseplay. You have already found the workaround, which is to briefly move the camera with the mouse as soon as you "un-click" the AD/CP dialogs. Once you do that, the camera can then be moved with the keyboard or game controller. It is an annoyance to be sure, but a minor one.

The LUA error is, I believe, unrelated.

**Comment by roddipoddi** [comment] 2019-09-26 13:53
ok, so the camera problem is already known? i also experience it after i return from the -esc- menü or the shop

the lua error might be unrelated but the game crashes afterwards

**Comment by Stephan-S** [comment] 2019-09-26 18:39
hey, I fixed the lua error. If this was indeed the cause of this, it should be fixed. If not, please reopen the issue.

Best regards,
Stephan

**Closed by Stephan-S** 2019-09-26 18:39 UTC
