### ISSUE TITLE
Waiting combine issue

### ISSUE THREAD

**Issue by Horozor** [Stephan-S/FS19_AutoDrive#276] opened 2019-07-08 21:01 UTC
When the tractor reaches the point near the field, it begins to slowly move in a circle while waiting for the combine to fill up. I use the latest version 1.0.3.5
![fsScreen_2019_07_08_23_55_11](https://user-images.githubusercontent.com/37561569/60842345-98350780-a1dc-11e9-8ae0-6e31e88f46dd.jpg)
![fsScreen_2019_07_08_23_55_43](https://user-images.githubusercontent.com/37561569/60842346-98350780-a1dc-11e9-9e14-4e40ee3489bb.jpg)
![fsScreen_2019_07_08_23_55_58](https://user-images.githubusercontent.com/37561569/60842347-98350780-a1dc-11e9-8918-7c1b618d7251.jpg)

**Comment by Stephan-S** [comment] 2019-07-08 21:06
Hey, could you try recalculating the Network and See If that helps?

**Comment by Horozor** [comment] 2019-07-08 21:07
@Horozor I try it many times, this not help

**Comment by Horozor** [comment] 2019-07-08 21:21
@Stephan-S I tried the old versions. The problem begins with the release version 1.0.3.4. 1.0.3.1 works well.

**Comment by Stephan-S** [comment] 2019-07-08 21:28
Could you Upload your Log File when this Happens? Thank you

**Comment by Horozor** [comment] 2019-07-08 21:32
@Stephan-S 
[Log](https://gist.github.com/Horozor/e83cfa6937f2196c35f27e696e0ae836)
I noticed that if you unhook the trailer, the tractor stops. But with the trailer starts to go in a circle.

**Comment by Opa-Andre** [comment] 2019-07-09 04:43
I guess the issue is in the course. The larger (longer) the vehicle combination is, the more likely such a problem occurs. The problem occurs when the vehicle cannot exactly reach its destination. I have therefore got used to create the tracks in such a way that the last track points before the destination **and especially the first track point** after a destination form a straight line. This allows the vehicles to align themselves. This seems to be confirmed as well as the tractor alone is able to reach the destination but not with the trailer...

**Comment by ploughedfieldman123** [comment] 2019-07-10 08:55
I always thought the route has to go into the fields to work. but this one by  Horozor  isnt even in the field, or am I wrong and the route also works out of the fields

**Comment by Opa-Andre** [comment] 2019-07-10 10:53
@ploughedfieldman123: Works also when being close to the fieldborder. This is different compared to CP, where you need to be inside the field borders for mode 2.

**Comment by ploughedfieldman123** [comment] 2019-07-10 10:56
Oh I always have the route in the fields. thats good to know then, I can change the routes better now.  how do you know where the field borders are. I play map Maxwell Manor

**Comment by Opa-Andre** [comment] 2019-07-11 04:37
Well, the field border is where no fruit is growing. :) Just drive your course so it stays outside of the fruit. Setup your harvester in AD to driving mode with the named point where your AD drivers are waiting to unload them, just don't activate your harvester in AD. That way they should find each other.

**Comment by ploughedfieldman123** [comment] 2019-07-11 08:52
ok thank you

**Comment by Enigma2223** [comment] 2019-07-14 15:44
Its because the distance to the unloading point is to short. In AutoDriveTrailerUtil.lua this distance is checked if it is below 100. In this case AD is unpaused, which causes the tractor to start driving in circles.
This is the code causing this:

![AutoDriveTrailerUtil](https://user-images.githubusercontent.com/52888964/61185900-cee8a300-a65e-11e9-955e-9af7cdaeac75.PNG)

**Comment by ploughedfieldman123** [comment] 2019-07-14 15:48
so if any destination point is below 100 it will go round in circles so if we changed that 100 would it work

**Comment by Enigma2223** [comment] 2019-07-14 16:35
I set it to 25 and it worked for me. Although I am not sure if this breaks something...

**Comment by fudoido** [comment] 2019-07-24 12:48
@Opa-Andre on courseplay you only need to be "inside" the field if you use the automatic combine detection. if you set the combine manually, it will also work if course is outside the fields, as i always do to avoid having machinery in the fields getting in the way of other working machinery.

**Comment by Stephan-S** [comment] 2019-08-27 12:54
This has been properly analyzed by @Enigma2223 and fixed in one of the lates releases, so I will close this here. Thank you!

**Closed by Stephan-S** 2019-08-27 12:54 UTC
