### ISSUE TITLE
[BUG] Points sinking into the ground, moving is almost impossible

### ISSUE THREAD

**Issue by Dennizzzzz** [Stephan-S/FS19_AutoDrive#1536] opened 2020-07-22 13:45 UTC
**AutoDrive Version:** 1.1.0.5-RC5 & 1.1.0.4
**Release or Custom Zip:** Release  
**Map (If applicable):** All  
**Vehicle / Type (If applicable):**   
**Multiplayer or Singleplayer:** Singleplayer  

When moving (and adding) points, at some places in the map Stappenbach 2020 the points are sinking into the ground when moving them around. Also adding points sink them into the ground. 

![image](https://user-images.githubusercontent.com/10248136/88183047-3ef61580-cc31-11ea-9cac-566723ddbc4e.png)

Changing the option 'Line height' to 'above tractor' shows them, but you are unable to move them around, because for moving you must select the 'bottom' red dot, moving them around using the upper dot does not work.

![image](https://user-images.githubusercontent.com/10248136/88183132-5a612080-cc31-11ea-87f2-0e1fc68ce9d5.png)

A workaround is to set the line height to above tractor, and remove the points, adding them again in the place you want them.

But it would be nice to be able to move them around with the upper red dot (above tractor dot). 
Or fix the problem with the sinking point into the ground. 
Another option would be able to move the points up and down yourself (with for example CTRL+ALT+mouse scroll).

**Comment by Iwan1803** [comment] 2020-07-22 14:27
> Or fix the problem with the sinking point into the ground.

Don't use 1.1.0.4 as this was fixed allready. Since recordings in newer versions almost works without any problems, there is no need to fix something.
Most of the time it's a problem of the map itself. The ground is then usually much deeper than the road and so the waypoints will "disappear" under it or the road elements are "special".

Does the problem always happen at this point on the map and where exactly on the map is this?

**Comment by Iwan1803** [comment] 2020-07-23 05:38
I've downloaded the map and got the same problem at this position. It's a small section where this happens.

@Axel32019 
how is it determined at which altitude the waypoint is set?

**Comment by Axel32019** [comment] 2020-07-25 13:45
The altitude is determined by the ground height at the waypoint. So this is an issue of the map.
You may try to level the ground at this position in the map to get the points visible.

**Comment by Dennizzzzz** [comment] 2020-08-03 08:55
Having the same problems on Sandy Bay map at most of the crossings. As soon as I want to move the points, there sink into the ground. During recording of the course there is no problem. But in edit mode is it really anoiying.

**Comment by Axel32019** [comment] 2020-09-30 17:27
@Dennizzzzz From my perspective this not a bug of AD, but still issue with the map(s) - I suggest to close this.

**Comment by Dennizzzzz** [comment] 2020-09-30 17:30
Alright, close it

**Closed** 2020-09-30 18:13 UTC
Labels: bug, waiting-for-user-input
