### ISSUE TITLE
Mode Unloading Combine - Not unloading at destination point

### ISSUE THREAD

**Issue by pCornetto** [Stephan-S/FS19_AutoDrive#818] opened 2019-11-07 22:36 UTC
Hello Stephan,
Hello Matteo,

unfortunately I've got a problem here with the mode for unloading of combine.

Once the unloader is set up for unloading of combine at field,
the point for unloading destination shown in HUD is switching to green.
(afaik this only should happen once driver actualy is heading for destination on track)

Combine then is unloaded by driver normaly.
HUD is showing unloading destination in green the whole time.

Once capacity for starting to unloading point is reached, unloader is heading to starting point.
The moment he reaches the starting point and is entering the track, point for unloading destination is switching to white in HUD and unloader normaly is heading for unloading destination.

Once unloader reaches unloading destination, origin point is switched to green in HUD and nothing more happens. The vehicle is not unloading and just stands there waiting doing nothing.

I've tried the latest commit of approx. 2 hours ago (Trailer will continue after unload is done now), but unfortunately nothing has changed.

I've also tried the "official" release version of 1.0.6.7.
https://github.com/Stephan-S/FS19_AutoDrive/blob/master/releases/1.0.6.7/FS19_AutoDrive.zip
With this version everything is working fine and unloading is done at unloading destination.
After unloading is finished driver continues back to origin also.

For both versions (commit and official) the Log-File is not showing any errors.

Have attached both Log-Files and a few screenshots.
Hope that this is helping you to figure out something for fixing this.

Highest respekt and thanks for your amazing work with this mod.

Greetings

 
[log_(not_working_commit_version).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3822022/log_.not_working_commit_version.txt)
[log_(working_official_version).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3822023/log_.working_official_version.txt)

<img width="943" alt="PIC_01" src="https://user-images.githubusercontent.com/55998595/68433326-88432980-01b6-11ea-86f2-dd910cbe84cd.png">
<img width="943" alt="PIC_02" src="https://user-images.githubusercontent.com/55998595/68433327-88432980-01b6-11ea-9fb1-1b6cd3bc62e5.png">
<img width="943" alt="PIC_03" src="https://user-images.githubusercontent.com/55998595/68433328-88dbc000-01b6-11ea-90bf-675279910f7e.png">
<img width="943" alt="PIC_04" src="https://user-images.githubusercontent.com/55998595/68433329-88dbc000-01b6-11ea-8a19-53c56452d78d.png">
<img width="943" alt="PIC_05" src="https://user-images.githubusercontent.com/55998595/68433330-88dbc000-01b6-11ea-8f75-4a08d6147c27.png">

**Comment by TyKonKet** [comment] 2019-11-08 11:53
Hey @pCornetto I'm having troubles reproducing your bug, I'm testing on Ravenport SP and combine unloading is working fine.
Are you playing in MP?

**Comment by raxtor** [comment] 2019-11-08 12:03
@TyKonKet https://github.com/Stephan-S/FS19_AutoDrive/issues/542#issuecomment-544287349

**Comment by pCornetto** [comment] 2019-11-08 13:19
Hey @TyKonKet 
thanks for coming back here so quickly.

I'm playing SP only - so no MP.

If you want to, I can start a new savegame on Ravenport this evening
and check if the problem occurse here as well.

Also could provide a copy of my savegame to you if needed / necessary.
(would require you to add a Mod-Map and 2 additional mods)

Just let me know if you need anything from me here.

Greetings

**Comment by TyKonKet** [comment] 2019-11-08 13:26
Yes, if you could do both it would be amazing helpful.

**Comment by raxtor** [comment] 2019-11-08 13:34
@TyKonKet its same proble I was reported earlier, its only combine mode and when unloader is rechead unloading point than from unknown reason it switches target to 1st one was created in network.

**Comment by TyKonKet** [comment] 2019-11-08 15:05
That's really strange since I've tested combine mode for many hours and I never noticed this bug

**Comment by raxtor** [comment] 2019-11-08 15:15
Try multiple Wilson trailer.. always bugged when 1st bin is filled up and should continue filling 2nd one, imho best way how to reproduce it... in closed thread I described it in a few comments. In fact I didnt test latest github version but I assume bug will be still there. https://github.com/Stephan-S/FS19_AutoDrive/issues/542#issuecomment-544044680

**Comment by raxtor** [comment] 2019-11-08 15:17
![66612960-0dd9b680-ebc4-11e9-847d-8746dd3bfe97](https://user-images.githubusercontent.com/831266/68487393-47ddbd00-0243-11ea-8ac6-c99693e56714.png)

**Comment by pCornetto** [comment] 2019-11-08 21:03
Hello again @TyKonKet 

I've tested the situation with commit release "Fixed #816".
Problem still exist, a slightly different behavior but generaly the same outcome.

Tested the commit with the same savegame like yesterday (Map HINTERKAIFECK).
First thing noticed: Once unloader is set up and approaching origin point
the HUD is showing origin and destination in white.

Once origin point is reached unloader waits for combine. Unloading of combine
is performed normaly. So nothing special at this part.

Once unloader is heading to starting point and enters track for driving to unloading destination
the origin and destination point are switched to green.

Once trigger (not waypoint) of unloading destination is reached, trailer is tipping and unloading.
If unloading process is finished, trailer is tipping back and nothing else is happening.
Vehicle just stands there waiting doing nothing with still everything green on HUD.

Cause nothing happend, I've clicked the button for "drive on". Vehicle is moving the last
meters until waypoint of unloading destination actualy is reached, the HUD then switched back
to everything showing in white and vehicle is waiting for combine.

Log is not showing any errors again.

[HINTERKAIFECK_log_(not_working_commit_Fixed_#816).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3826145/HINTERKAIFECK_log_.not_working_commit_Fixed_.816.txt)

Following some screenshots

<img width="943" alt="PIC_06" src="https://user-images.githubusercontent.com/55998595/68508683-46c28500-026f-11ea-9c0c-56c839d28ac5.png">
<img width="943" alt="PIC_07" src="https://user-images.githubusercontent.com/55998595/68508709-5346dd80-026f-11ea-8914-2c1c0a2ed544.png">
<img width="943" alt="PIC_08" src="https://user-images.githubusercontent.com/55998595/68508734-6b1e6180-026f-11ea-952e-79934b6192d4.png">
<img width="943" alt="PIC_09" src="https://user-images.githubusercontent.com/55998595/68508746-74a7c980-026f-11ea-8295-51985e251b37.png">
<img width="943" alt="PIC_10" src="https://user-images.githubusercontent.com/55998595/68508750-78d3e700-026f-11ea-82c3-3c170bec28a9.png">
<img width="943" alt="PIC_11" src="https://user-images.githubusercontent.com/55998595/68508754-7c676e00-026f-11ea-8b24-d1c9f61d84af.png">



Like requested I have also started a new savegame on RAVENPORT for testing.

Behavior is slightly different here again, but outcome remains the same.

Unloader is waiting at origin point for combine and unloading process of combine
is performed normaly. HUD showing everything in white. So nothing special here.

Once the vehicle returns to starting point and enters track origin and destination point remain white.

Once unloading destination is reached, the vehicle stops and nothing more happens.
Driver just standing there waiting doing nothing.

If the "drive on" button is clicked, vehicle returns to origin point.
HUD still is showing everythin in white.

Log again is not showing any errors.

[RAVENPORT_log_(not_working_commit_Fixed_#816).txt](https://github.com/Stephan-S/FS19_AutoDrive/files/3826179/RAVENPORT_log_.not_working_commit_Fixed_.816.txt)

Following a few screenshots

<img width="943" alt="PIC_12_(RP)" src="https://user-images.githubusercontent.com/55998595/68509276-e2a0c080-0270-11ea-99de-90603abe3af5.png">
<img width="943" alt="PIC_13_(RP)" src="https://user-images.githubusercontent.com/55998595/68509285-e7fe0b00-0270-11ea-9ae6-96e2fb793cb9.png">
<img width="943" alt="PIC_14_(RP)" src="https://user-images.githubusercontent.com/55998595/68509291-eb919200-0270-11ea-87bd-1450e2baa2c0.png">
<img width="943" alt="PIC_15_(RP)" src="https://user-images.githubusercontent.com/55998595/68509304-efbdaf80-0270-11ea-9282-ac61f0773668.png">



If you would like to take a look on my savegame yourself, you will find all files here:
https://drive.google.com/drive/folders/1VMT742t9_Tj4Uayt0DP63q-Ky2OESS6l?usp=sharing

ZIP is including both savegames (mod-map and Ravenport) and mods you would need.


Sorry to bother you with this issue.
I hope you can figure something out here.

Thanks again for your great work.

Greetings

**Comment by Stephan-S** [comment] 2019-11-09 19:57
Should all be working now.
You just caught a bad week for updating your AutoDrive version.
We both introduced some bugs but they should be fixed now :-)

**Comment by Stephan-S** [comment] 2019-11-10 08:46
I'll close this issue for now. If the bug/s are still present in the current sources, please reopen. Thank you

**Closed by Stephan-S** 2019-11-10 08:46 UTC
Labels: further investigations
